### ISSUE TITLE
Uninstall Distro crashed 

### ISSUE THREAD

**Issue by nobicycle** [mbusb/multibootusb#103]
Hi,

Uninstall Distro crashed as follows:

$ multibootusb-pkexec 
Starting multibootusb GUI...
Using pyudev for detecting USB drives...
Cleaning old multibootusb directory...
Extracting syslinux to multibootusb directory...
Host OS is 64 bit...
Extracting syslinux 64 bit...
Extracting syslinux modules to multibootusb directory...
Installed distro type is arch
/run/media/user/TOSHIBA(1)/multibootusb/manjaro-xfce-17.0-stable-x86_64/multibootusb.cfg
Exception in thread uninstall_progress:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/scripts/uninstall_distro.py",
line 47, in unin_distro uninstall_distro()
  File "/usr/lib/python3.6/site-packages/scripts/uninstall_distro.py",
line 116, in uninstall_distro os.chmod(os.path.join(path, name), 0o777)
OSError: [Errno 30] Read-only file system:
'/run/media/user/TOSHIBA(1)/multibootusb/manjaro-xfce-17.0-stable-x86_64/isolinux/ldlinux.sys'

Distro uninstall is complete...
Updating syslinux.cfg file...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scripts/mbusb_gui.py", line
314, in uninstall_sys_file_update update_sys_cfg_file()
  File "/usr/lib/python3.6/site-packages/scripts/uninstall_distro.py",
line 158, in update_sys_cfg_file config_file = open(sys_cfg_file, "w")
OSError: [Errno 30] Read-only file system:
'/run/media/user/TOSHIBA(1)/multibootusb/syslinux.cfg' /usr/bin/multibootusb-pkexec:
line 6: 21996 Aborted                 (core dumped) pkexec
--disable-internal-agent "/usr/bin/multibootusb" "$@"

**Comment by mbusb** [comment]
This issue was fixed log ago. I am not sure why this occur again. I have done many testing my end but could not reproduce this issue.

**Comment by nobicycle** [comment]
I can't reproduce it now also.
I will close.
Thanks

**Comment by khalil2535** [comment]
Got this today :disappointed: 

Selected device /dev/sda
Device /dev/sda is a GPT disk...
USB disk is not mounted and can't update list widget...
Selected device /dev/sdb1
Device /dev/sdb1 is a MBR disk...
Installed distro type is debian-install
Exception in thread uninstall_progress:                                       |
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/scripts/uninstall_distro.py", line 46, in run
    do_uninstall_distro(self.target_distro, self.uninstall_distro_dir_name)
  File "/usr/local/lib/python3.5/dist-packages/scripts/uninstall_distro.py", line 131, in do_uninstall_distro
    os.chmod(os.path.join(path, name), 0o777)
OSError: [Errno 30] Read-only file system: '/run/media/root/MJRO1802/multibootusb/debian-9.6.0-amd64-xfce-CD-1/isolinux/ldlinux.sys'

Distro uninstall is complete...
