### ISSUE TITLE
Crash when /dev/sdb is not readable

### ISSUE THREAD

**Issue by alandmoore** [mbusb/multibootusb#180]
Using 8.8.0-3 from AUR on arch linux.

`/dev/sdb` thru `/dev/sde` on my system are taken up by a USB card reader device.  My USB drive shows up as `/dev/sdf`.

Because I have no cards installed in the card reader, `fdisk -l /dev/sdb` returns a non-zero result and multibootusb will not start on the system.  Even if I specify the target as `/dev/sdf`, the program still scans all the drives and throws an exception.

The traceback is:

```
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
	/dev/sdb
	/dev/sdc
	/dev/sdd
	/dev/sde
	/dev/sdf
	/dev/sdf1
Selected device /dev/sdb
fdisk: cannot open /dev/sdb: No medium found
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scripts/usb.py", line 406, in details
    details = details_udev(usb_disk_part)
  File "/usr/lib/python3.6/site-packages/scripts/usb.py", line 222, in details_udev
    fdisk_cmd_out = subprocess.check_output('fdisk -l ' + usb_disk_part, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'fdisk -l /dev/sdb' returned non-zero exit status 1.

```

**Comment by hubitor** [comment]
Same here...Also using 8.8.0 on Arch Linux. When I start multibootusb it asks for password and then crashes. Starting it from the terminal I see the aforementioned error plus another one:

****$ /usr/bin/multibootusb-pkexec****

```
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
        /dev/sde
        /dev/sdf
        /dev/sdg
        /dev/sdh
Selected device /dev/sde
**fdisk: cannot open /dev/sde: No medium found**
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scripts/usb.py", line 406, in details
    details = details_udev(usb_disk_part)
  File "/usr/lib/python3.6/site-packages/scripts/usb.py", line 222, in details_udev
    fdisk_cmd_out = subprocess.check_output('fdisk -l ' + usb_disk_part, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
**subprocess.CalledProcessError: Command 'fdisk -l /dev/sde' returned non-zero exit status 1.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scripts/mbusb_gui.py", line 148, in onComboChange
    config.usb_details = usb.details(config.usb_disk)
  File "/usr/lib/python3.6/site-packages/scripts/usb.py", line 408, in details
    details = details_udisks2(usb_disk_part)
  File "/usr/lib/python3.6/site-packages/scripts/usb.py", line 281, in details_udisks2
    mount_point = bd.Get('org.freedesktop.UDisks2.Filesystem', 'MountPoints', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.UDisks2.Filesystem'
/usr/bin/multibootusb-pkexec: line 22:  3306 Aborted                 (core dumped) pkexec --disable-internal-agent "/usr/bin/multibootusb" "$@"

```
It is obvious that the command 'fdisk -l /dev/sde' fails since there is no sde.
