### ISSUE TITLE
Wont start on arch linux via source code or AUR

### ISSUE THREAD

**Issue by GNUGradyn** [mbusb/multibootusb#194]
This is with the source code, but the same error appears via the AUR.

```
GROOD-COMPOOTER>multibootusb-master>0$sudo python3 ./multibootusb
Running multibootusb version 8.8.0 from source...
Starting multibootusb GUI...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
	/dev/sdg
	/dev/sdg1
	/dev/sdg2
	/dev/sdc
	/dev/sdd
	/dev/sde
	/dev/sdf
Selected device /dev/sdc
fdisk: cannot open /dev/sdc: No medium found
Traceback (most recent call last):
  File "/home/gradyn/Downloads/multibootusb-master/scripts/usb.py", line 406, in details
    details = details_udev(usb_disk_part)
  File "/home/gradyn/Downloads/multibootusb-master/scripts/usb.py", line 222, in details_udev
    fdisk_cmd_out = subprocess.check_output('fdisk -l ' + usb_disk_part, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'fdisk -l /dev/sdc' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gradyn/Downloads/multibootusb-master/scripts/mbusb_gui.py", line 148, in onComboChange
    config.usb_details = usb.details(config.usb_disk)
  File "/home/gradyn/Downloads/multibootusb-master/scripts/usb.py", line 408, in details
    details = details_udisks2(usb_disk_part)
  File "/home/gradyn/Downloads/multibootusb-master/scripts/usb.py", line 281, in details_udisks2
    mount_point = bd.Get('org.freedesktop.UDisks2.Filesystem', 'MountPoints', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.UDisks2.Filesystem'
Aborted
```

**Comment by GNUGradyn** [comment]
EDIT: works fine from commandline

**Comment by wefixit-AT** [comment]
On my side it did not start from the shell. Can you provide the command you used?

This did not work:
`sudo` multibootusb -i dban-2.3.0_i586.iso -t /dev/sdl1

**Comment by alandmoore** [comment]
This looks like the same issue as #180

**Comment by swUchicago** [comment]
Encounter the same problem. It seems that I did not format the USB correctly. Reformat the USB, now works.
