### ISSUE TITLE
Problems to debug multibootusb

### ISSUE THREAD

**Issue by vk496** [mbusb/multibootusb#219]
OS: Arch Linux
multibootusb version: **8.8.0**

When try to debug, recieve error:

```bash
$ sudo multibootusb -c -i wifislax64-final.iso -t /dev/sdb1 -d
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scripts/debug.py", line 6, in <module>
    from colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/multibootusb", line 151, in <module>
    from scripts.debug import colors
  File "/usr/lib/python3.6/site-packages/scripts/debug.py", line 11, in <module>
    raise e
  File "/usr/lib/python3.6/site-packages/scripts/debug.py", line 9, in <module>
    from .colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'scripts.colorama'
```

**Comment by vk496** [comment]
In the devel branch, work propperly
