### ISSUE TITLE
Wifislax ISO error

### ISSUE THREAD

**Issue by vk496** [mbusb/multibootusb#220]
OS: Arch Linux
multibootusb version: **8.8.0**
ISO: [wifislax64-1.1-final](https://www.wifislax.com/wifislax64-1-1-final/)

Multibootusb crash when select Wifislax ISO:
```bash
$ sudo multibootusb -c -i wifislax64-final.iso -t /dev/sdb1
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb from Command line...
25008
True
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Executing ==> 7z -ssc-  x -y "wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.lst" -r 2> /dev/null
Traceback (most recent call last):
  File "/usr/sbin/multibootusb", line 170, in <module>
    cli_install_distro()
  File "/usr/lib/python3.6/site-packages/scripts/mbusb_cli.py", line 52, in cli_install_distro
    iso_install(config.image_path)
  File "/usr/lib/python3.6/site-packages/scripts/mbusb_cli.py", line 71, in iso_install
    _distro = distro(iso_cfg_ext_dir(), iso_image)
  File "/usr/lib/python3.6/site-packages/scripts/distro.py", line 26, in distro
    iso_file_list = _7zip.list_iso(iso_link)
  File "/usr/lib/python3.6/site-packages/scripts/_7zip.py", line 77, in list_iso
    _cmd_out = subprocess.check_output(_cmd, stderr=subprocess.PIPE, shell=True).decode('utf-8', 'ignore').splitlines()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '7z l "wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
```

Output of `7z l "wifislax64-final.iso"`:
```bash
$ 7z l "wifislax64-final.iso"

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=es_ES.utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (306D4),ASM,AES-NI)

Scanning the drive for archives:
1 file, 2178940928 bytes (2078 MiB)

Listing archive: wifislax64-final.iso

--
Path = wifislax64-final.iso
Type = Iso
ERRORS:
Unexpected end of archive
Physical Size = 8796092989440
Created = 2017-07-28 16:00:49
Modified = 2017-07-28 16:00:49

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2016-08-24 09:33:16 D....                            EFI
2017-07-17 01:49:16 D....                            EFI/BOOT
2016-09-17 02:48:20 .....      1271672      1271672  EFI/BOOT/MokManager.efi
2016-05-05 17:27:00 .....            0            0  EFI/BOOT/WIFISLAXLIVE
2016-09-17 02:48:20 .....      1289424      1289424  EFI/BOOT/bootx64.efi
2016-05-18 08:11:58 .....           89           89  EFI/BOOT/grub-embedded.cfg
2016-12-17 01:03:00 .....         1965         1965  EFI/BOOT/grub.cfg
2016-09-18 16:39:04 .....      1074464      1074464  EFI/BOOT/grubx64.efi
2017-07-17 01:49:12 .....         3120         3120  EFI/BOOT/help.txt
2016-07-28 21:23:28 .....         2642         2642  EFI/BOOT/kbd.cfg
2016-07-28 21:23:28 .....         2275         2275  EFI/BOOT/lang.cfg
2016-09-18 23:01:50 D....                            EFI/BOOT/memtest
2016-08-05 01:00:04 D....                            EFI/BOOT/memtest/BENCHMAR
2016-08-05 01:00:04 .....         6823         6823  EFI/BOOT/memtest/MT86.PNG
2016-08-05 01:00:04 .....      2358510      2358510  EFI/BOOT/memtest/UNIFONT.BIN
2016-08-05 01:00:04 .....       981904       981904  EFI/BOOT/memtest/memtestx64.efi
2017-04-05 02:43:02 D....                            EFI/BOOT/theme
2016-05-05 17:27:00 .....        80015        80015  EFI/BOOT/theme/dejavusansmono10.pf2
2016-05-05 17:27:00 .....        85801        85801  EFI/BOOT/theme/dejavusansmono12.pf2
2016-05-05 17:27:00 .....        69887        69887  EFI/BOOT/theme/dejavusansmono5.pf2
2015-12-01 23:08:50 .....      2560080      2560080  EFI/BOOT/theme/unicode.pf2
2017-04-05 02:32:02 .....       589263       589263  EFI/BOOT/theme/wifislax.png
2017-04-05 02:42:48 .....         1336         1336  EFI/BOOT/theme/wifislax.txt
2016-07-28 21:23:34 .....        63398        63398  EFI/BOOT/tz.cfg
2016-09-17 02:48:20 .....          971          971  EFI/BOOT/wifislax.cer
2017-07-17 01:47:46 D....                            boot
2016-10-01 08:21:56 .....        93873        93873  boot/Linux_Wifislax_Boot_Installer.com
2014-02-12 00:49:50 .....       180736       180736  boot/Windows_Wifislax_Boot_Installer.exe
2017-07-17 02:28:44 .....      5948528      5948528  boot/initrd.xz
2017-07-19 05:18:34 D....                            boot/kernel_configs
2017-07-19 03:36:54 .....       171747       171747  boot/kernel_configs/4.10.config
2017-07-19 03:41:04 .....       173907       173907  boot/kernel_configs/4.11.config
2017-07-19 04:20:58 .....       176260       176260  boot/kernel_configs/4.12.config
2017-07-19 05:00:40 .....       178113       178113  boot/kernel_configs/4.13.config
2017-05-17 06:47:40 .....       169027       169027  boot/kernel_configs/4.9.28.config
2017-03-23 01:04:26 .....          416          416  boot/kernel_configs/changes-slackware-huge
2016-07-01 10:19:04 .....       150024       150024  boot/memtest
2017-04-07 01:42:00 D....                            boot/syslinux
2016-11-16 16:33:36 .....      4423680      4423680  boot/syslinux/efiboot.img
2016-07-01 13:19:22 .....          969          969  boot/syslinux/f2.txt
2016-07-31 07:12:52 .....         1214         1214  boot/syslinux/f3.txt
2016-07-01 11:19:04 .....         1214         1214  boot/syslinux/f4.txt
2016-07-31 07:11:56 .....          849          849  boot/syslinux/f5.txt
2016-07-01 11:19:04 .....           50           50  boot/syslinux/iso.sort
2016-09-09 21:35:22 .....        24576        24576  boot/syslinux/isolinux.bin
2017-07-28 16:00:49 .....         2048         2048  boot/syslinux/isolinux.boot
2016-07-29 08:04:28 .....           25           25  boot/syslinux/isolinux.cfg
2016-12-13 09:10:12 .....         1408         1408  boot/syslinux/lang.cfg
2016-12-23 23:05:38 .....        37888        37888  boot/syslinux/ldlinux.sys
2016-12-17 00:49:08 D....                            boot/syslinux/menu
2016-07-01 13:19:08 .....          256          256  boot/syslinux/menu/be-latin1.ktl
2016-07-01 13:19:08 .....          256          256  boot/syslinux/menu/br-abnt2.ktl
2016-07-01 13:19:10 .....          256          256  boot/syslinux/menu/de-latin1-nodeadkeys.ktl
2016-07-01 13:19:12 .....          256          256  boot/syslinux/menu/de-latin1.ktl
2016-07-01 13:19:12 .....          256          256  boot/syslinux/menu/es.ktl
2013-06-05 11:56:24 .....          256          256  boot/syslinux/menu/es_m.ktl
2016-07-01 13:19:14 .....          256          256  boot/syslinux/menu/fr-latin9.ktl
2016-07-01 13:19:16 .....          256          256  boot/syslinux/menu/it.ktl
2016-07-01 13:19:16 .....          256          256  boot/syslinux/menu/jp106.ktl
2016-07-01 13:19:22 .....         1510         1510  boot/syslinux/menu/kbd.cfg
2016-12-13 13:56:44 .....         2072         2072  boot/syslinux/menu/lang_be.cfg
2016-12-13 13:56:12 .....         2056         2056  boot/syslinux/menu/lang_br.cfg
2016-12-13 13:55:38 .....         2224         2224  boot/syslinux/menu/lang_de.cfg
2016-12-13 13:55:04 .....         2071         2071  boot/syslinux/menu/lang_de_ch.cfg
2016-12-13 09:20:00 .....         1972         1972  boot/syslinux/menu/lang_es.cfg
2016-12-13 09:19:30 .....         2085         2085  boot/syslinux/menu/lang_fr.cfg
2016-12-13 09:18:58 .....         2085         2085  boot/syslinux/menu/lang_fr_ch.cfg
2016-12-13 09:18:30 .....         1972         1972  boot/syslinux/menu/lang_gb.cfg
2016-12-13 09:17:56 .....         1972         1972  boot/syslinux/menu/lang_it.cfg
2016-12-13 09:17:16 .....         2014         2014  boot/syslinux/menu/lang_ja.cfg
2016-12-13 09:16:30 .....         1972         1972  boot/syslinux/menu/lang_nl.cfg
2016-12-13 09:15:58 .....         2070         2070  boot/syslinux/menu/lang_pt.cfg
2016-12-13 09:15:20 .....         2028         2028  boot/syslinux/menu/lang_ru.cfg
2016-12-13 09:14:44 .....         1972         1972  boot/syslinux/menu/lang_us.cfg
2016-12-13 09:13:40 .....         2018         2018  boot/syslinux/menu/menu_be.cfg
2016-12-13 09:13:30 .....         2017         2017  boot/syslinux/menu/menu_br.cfg
2016-12-13 09:13:20 .....         2029         2029  boot/syslinux/menu/menu_de.cfg
2016-12-13 09:13:12 .....         2021         2021  boot/syslinux/menu/menu_de_ch.cfg
2016-12-13 09:13:02 .....         2011         2011  boot/syslinux/menu/menu_es.cfg
2016-12-13 09:12:52 .....         2018         2018  boot/syslinux/menu/menu_fr.cfg
2016-12-13 09:12:40 .....         2021         2021  boot/syslinux/menu/menu_fr_ch.cfg
2016-12-13 09:12:32 .....         2011         2011  boot/syslinux/menu/menu_gb.cfg
2016-12-13 09:12:14 .....         2011         2011  boot/syslinux/menu/menu_it.cfg
2016-12-13 09:12:02 .....         2014         2014  boot/syslinux/menu/menu_ja.cfg
2016-12-13 09:11:54 .....         2011         2011  boot/syslinux/menu/menu_nl.cfg
2016-12-13 09:11:44 .....         2018         2018  boot/syslinux/menu/menu_pt.cfg
2016-12-13 09:11:36 .....         2015         2015  boot/syslinux/menu/menu_ru.cfg
2016-12-13 09:11:26 .....         2011         2011  boot/syslinux/menu/menu_us.cfg
2016-07-01 13:19:18 .....          256          256  boot/syslinux/menu/nl.ktl
2016-07-01 13:19:18 .....          256          256  boot/syslinux/menu/pt-latin1.ktl
2016-07-01 13:19:20 .....          256          256  boot/syslinux/menu/ru_win.ktl
2016-07-01 13:19:10 .....          256          256  boot/syslinux/menu/uk.ktl
2016-07-01 13:19:22 .....          256          256  boot/syslinux/menu/us.ktl
2016-12-17 00:49:04 .....         2404         2404  boot/syslinux/menu/vesamenu.cfg
2016-07-26 10:11:56 .....          472          472  boot/syslinux/message.txt
2016-07-29 08:04:40 .....           25           25  boot/syslinux/syslinux.cfg
2016-05-24 23:54:22 .....        87040        87040  boot/syslinux/syslinux.exe
2016-07-01 13:19:22 .....         5146         5146  boot/syslinux/ter-i16v.psf
2016-05-24 23:54:22 .....       154128       154128  boot/syslinux/vesamenu.c32
2017-04-07 01:42:00 .....       140741       140741  boot/syslinux/wifislax.png
2017-07-28 15:17:54 .....      8305216      8305216  boot/vmlinuz
2017-07-28 15:27:16 D....                            wifislax64
2017-07-19 05:19:00 D....                            wifislax64/base
2017-07-28 15:26:50 D....                            wifislax64/base/Kernel
2017-07-28 19:18:24 .....     47689728     47689728  wifislax64/base/Kernel/000-Kernel-4.9.40-x86_64-1wifislax.xzm
2017-07-22 03:15:38 D....                            wifislax64/base/Multilib
2017-07-28 15:09:42 .....    130912256    130912256  wifislax64/base/Multilib/001-Slackware-multilib.xzm
2017-07-28 15:07:30 .....      2215936      2215936  wifislax64/base/Multilib/002-Wireless_Compat32.xzm
2017-07-28 15:07:26 .....         8192         8192  wifislax64/base/Multilib/003-compat32_updater-1.0-noarch-1wifislax.xzm
2017-07-22 05:32:40 D....                            wifislax64/base/SBo
2017-07-28 16:53:26 .....     13107200     13107200  wifislax64/base/SBo/004-SBo_Accessibility.xzm
2017-07-28 16:53:50 .....      5607424      5607424  wifislax64/base/SBo/005-SBo_Audio.xzm
2017-07-28 16:54:14 .....      1179648      1179648  wifislax64/base/SBo/006-SBo_Desktop.xzm
2017-07-28 16:55:26 .....     26357760     26357760  wifislax64/base/SBo/007-SBo_Development.xzm
2017-07-28 16:55:46 .....       208896       208896  wifislax64/base/SBo/008-SBo_Games.xzm
2017-07-28 16:56:10 .....      3297280      3297280  wifislax64/base/SBo/009-SBo_Graphics.xzm
2017-07-28 17:01:18 .....    163172352    163172352  wifislax64/base/SBo/010-SBo_Libraries.xzm
2017-07-28 17:01:40 .....       393216       393216  wifislax64/base/SBo/011-SBo_Misc.xzm
2017-07-28 17:02:44 .....     32313344     32313344  wifislax64/base/SBo/012-SBo_Multimedia.xzm
2017-07-28 17:04:02 .....     86659072     86659072  wifislax64/base/SBo/013-SBo_Network.xzm
2017-07-28 17:04:50 .....      7036928      7036928  wifislax64/base/SBo/014-SBo_Perl.xzm
2017-07-28 17:06:12 .....     31907840     31907840  wifislax64/base/SBo/015-SBo_Python.xzm
2017-07-28 17:06:36 .....       876544       876544  wifislax64/base/SBo/016-SBo_Ruby.xzm
2017-07-28 17:07:24 .....     24408064     24408064  wifislax64/base/SBo/017-SBo_System.xzm
2017-06-25 22:11:44 D....                            wifislax64/base/Slackware
2017-07-28 16:53:24 .....     38793216     38793216  wifislax64/base/Slackware/018-Slack_a.xzm
2017-07-28 16:55:38 .....    106999808    106999808  wifislax64/base/Slackware/019-Slack_ap.xzm
2017-07-28 17:03:42 .....    261939200    261939200  wifislax64/base/Slackware/020-Slack_d.xzm
2017-07-28 17:06:00 .....    106086400    106086400  wifislax64/base/Slackware/021-Slack_kde.xzm
2017-07-28 17:06:50 .....     42033152     42033152  wifislax64/base/Slackware/022-Slack_kdei-14.2-x86_64.xzm
2017-07-28 17:10:54 .....    206237696    206237696  wifislax64/base/Slackware/023-Slack_l.xzm
2017-07-28 17:12:32 .....     78311424     78311424  wifislax64/base/Slackware/024-Slack_n.xzm
2017-07-28 17:13:26 .....     46243840     46243840  wifislax64/base/Slackware/025-Slack_t.xzm
2017-07-28 17:13:50 .....      3252224      3252224  wifislax64/base/Slackware/026-Slack_tcl.xzm
2017-07-28 17:15:04 .....     65200128     65200128  wifislax64/base/Slackware/027-Slack_x-1.17.xzm
2017-07-28 17:16:18 .....     66265088     66265088  wifislax64/base/Slackware/028-Slack_xap.xzm
2017-07-28 02:30:48 D....                            wifislax64/base/Wifislax
2017-07-28 16:35:02 .....    104112128    104112128  wifislax64/base/Wifislax/029-Firmwares-20170622-noarch-4wifislax.xzm
2017-07-28 16:36:10 .....     66449408     66449408  wifislax64/base/Wifislax/030-Google-chrome-60.0.3112.78-x86_64-1wifislax.xzm
2017-07-28 15:41:38 .....    167350272    167350272  wifislax64/base/Wifislax/031-Jdk-8u144-x64-1wifislax.xzm
2017-07-28 16:38:08 .....      7749632      7749632  wifislax64/base/Wifislax/032-Wifislax_Development.xzm
2017-07-28 16:38:48 .....     25190400     25190400  wifislax64/base/Wifislax/033-Wifislax_Libraries.xzm
2017-07-28 16:39:08 .....       811008       811008  wifislax64/base/Wifislax/034-Wifislax_Misc.xzm
2017-07-28 16:39:36 .....     12128256     12128256  wifislax64/base/Wifislax/035-Wifislax_Multimedia.xzm
2017-07-28 15:28:32 .....     83136512     83136512  wifislax64/base/Wifislax/036-Wifislax_Network.xzm
2017-07-28 16:41:26 .....      2449408      2449408  wifislax64/base/Wifislax/037-Wifislax_Perl.xzm
2017-07-28 16:41:50 .....      3149824      3149824  wifislax64/base/Wifislax/038-Wifislax_Python.xzm
2017-07-28 16:42:40 .....     40042496     40042496  wifislax64/base/Wifislax/039-Wifislax_Ruby.xzm
2017-07-28 16:43:14 .....     14721024     14721024  wifislax64/base/Wifislax/040-Wifislax_Installer.xzm
2017-07-28 20:55:46 .....     20725760     20725760  wifislax64/base/Wifislax/041-Wifislax_Desktop.xzm
2017-07-28 15:27:14 .....        27203        27203  wifislax64/cambios.txt
2016-09-09 23:27:14 .....          729          729  wifislax64/make_iso
2017-07-28 15:43:49 D....                            wifislax64/modules
2017-07-23 20:39:02 D....                            wifislax64/optional
2016-08-14 02:54:48 D....                            wifislax64/rootcopy
                    .....         2048         2048  [BOOT]/1-Boot-NoEmul.img
                    .....      4423680      4423680  [BOOT]/2-Boot-NoEmul.img
------------------- ----- ------------ ------------  ------------------------
2017-07-28 20:55:46         2182120892   2182120892  138 files, 19 folders

Errors: 1
```

Salu2

**Comment by alandmoore** [comment]
Looks like this is fixed in devel.

**Comment by vk496** [comment]
I've tried with the devel branch, but recieve this:

```$ sudo python ./multibootusb -d
=== DEBUG ENABLED ===
Running multibootusb version 8.8.0 from source...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
	/dev/sdb
	/dev/sdb1
	/dev/sdb2
Selected device /dev/sdb
USB disk is not mounted and can't update list widget...
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.lst" -r 2> /dev/null
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
Persistence is not available for wifislax64-final.iso
QXcbConnection: XCB error: 3 (BadWindow), sequence: 864, resource id: 6481953, major code: 40 (TranslateCoords), minor code: 0
Selected device /dev/sdb1
MultiBoot Install: USB Disk: /dev/sdb1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 5843-A116
MultiBoot Install: USB mount path: /run/media/root/5843-A116
MultiBoot Install: Disk total size: 12.7G
MultiBoot Install: Disk used size: 8.0K
MultiBoot Install: Disk free size: 12.7G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: JetFlash
MultiBoot Install: Disk model: Transcend_16GB
MultiBoot Install: ISO file: wifislax64-final.iso
MultiBoot Install: Distro type detected: wifislax
Persistence chosen is 0B
Copying multibootusb directory to /run/media/root/5843-A116
EFI/BOOT directory does not exist. Creating new.
Copying EFI directory to /run/media/root/5843-A116
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
Installing wifislax64-final.iso on /run/media/root/5843-A116/multibootusb/wifislax64-final
Executing ==> 7z -ssc-  x -y -o"/run/media/root/5843-A116/multibootusb/wifislax64-final" "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null
ISO extracted successfully. Sync is in progress...########################### |
Distro extraction completed...################################################|
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
Distro does not use isolinux for booting ISO.
Traceback (most recent call last):
  File "/home/vk496/NetBeansProjects/multibootusb/scripts/mbusb_gui.py", line 327, in install_syslinux
    syslinux_default(config.usb_disk)
  File "/home/vk496/NetBeansProjects/multibootusb/scripts/syslinux.py", line 122, in syslinux_default
    mbr_bin = get_mbr_bin_path(usb_disk)
  File "/home/vk496/NetBeansProjects/multibootusb/scripts/syslinux.py", line 72, in get_mbr_bin_path
    if gpt_part_table(usb_disk) is False:
  File "/home/vk496/NetBeansProjects/multibootusb/scripts/syslinux.py", line 30, in gpt_part_table
    win_usb_disk_no = str(usb.get_physical_disk_number(config.usb_disk))
  File "/home/vk496/NetBeansProjects/multibootusb/scripts/usb.py", line 433, in get_physical_disk_number
    import wmi
ModuleNotFoundError: No module named 'wmi'
Abortado
```

Using this:

` sudo pip install wmi-client-wrapper`

Not fix it.

Also, if I try to install it again, show me that the ISO is alredy installed but not appear in the list.

Salu2

**Comment by mbusb** [comment]
Can you try the new release and report back.

**Comment by vk496** [comment]
Seems still not work:

```bash
$ sudo multibootusb -c -i ~/Downloads/wifislax64/wifislax64-final.iso -t /dev/sdb1 -y -d
=== DEBUG ENABLED ===
Running multibootusb version 8.9.0 from source...
Starting multibootusb from Command line...
25008
True
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" -o/root/.multibootusb/iso_cfg_ext_dir "*.lst" -r 2> /dev/null
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
Initiating installation process for wifislax64-final
Detected distro type is    :wifislax

Selected ISO is          :"wifislax64-final.iso"
Selected target device is  :"/dev/sdb1"
Skipping user confirmation for /home/vk496/Downloads/wifislax64/wifislax64-final.iso
Copying multibootusb directory to /run/media/vk496/74CB-696F
EFI/BOOT directory does not exist. Creating new.
Copying EFI directory to /run/media/vk496/74CB-696F
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.                                                                         |
Installing wifislax64-final.iso on /run/media/vk496/74CB-696F/multibootusb/wifislax64-final
Executing ==> 7z -ssc-  x -y -o"/run/media/vk496/74CB-696F/multibootusb/wifislax64-final" "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null
ISO extracted successfully. Sync is in progress...###########################################################################################################################################|
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
Command '7z l "/home/vk496/Downloads/wifislax64/wifislax64-final.iso" 2> /dev/null' returned non-zero exit status 2.
Distro does not use isolinux for booting ISO.
Traceback (most recent call last):
  File "/usr/sbin/multibootusb", line 188, in <module>
    cli_install_distro()
  File "/usr/lib/python3.6/site-packages/scripts/mbusb_cli.py", line 69, in cli_install_distro
    iso_install(config.image_path)
  File "/usr/lib/python3.6/site-packages/scripts/mbusb_cli.py", line 114, in iso_install
    syslinux_default(config.usb_disk)
  File "/usr/lib/python3.6/site-packages/scripts/syslinux.py", line 103, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: must be str, not bool
```

**Comment by mbusb** [comment]
Downloading the ISO for checking...

**Comment by mbusb** [comment]
The last issue was different from the one reported earlier. It is fixed in the latest commit on devel branch. If you confirm then I will close the issue.

**Comment by vk496** [comment]
ups. Yes, you right. Different issue here...
