### ISSUE TITLE
undefined symbol: XML_SetHashSalt

### ISSUE THREAD

**Issue by tkossak** [mbusb/multibootusb#233]
Hi,
When i select `/dev/sdb1` in listbox i get the error `/usr/bin/python3: symbol lookup error: /usr/bin/python3: undefined symbol: XML_SetHashSalt`. Any idea what's wrong? Thank you

Linux Mint 18.1 Serena x64 Cinnamon
USB has one partition, of 31GB size with vfat filesystem.
I installed multibootusb by downloading `python3-multibootusb_8.8.0-1_all.deb`. Maybe it doesn't support Linux Mint?

```
$ sudo multibootusb
Running multibootusb version 8.8.0 from installed system...
Starting multibootusb GUI...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
        /dev/sdb
        /dev/sdb1
Selected device /dev/sdb
USB disk is not mounted and can't update list widget...
Selected device /dev/sdb1
/usr/bin/python3: symbol lookup error: /usr/bin/python3: undefined symbol: XML_SetHashSalt

$ mount | grep sdb
/dev/sdb1 on /mnt/usb type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

$ sudo multibootusb --version
multibootusb version: 8.8.0

$ sudo multibootusb --debug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 6, in <module>
    from colorama import init as colorama_init, Fore, Back, Style
ImportError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 151, in <module>
    from scripts.debug import colors
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 11, in <module>
    raise e
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 9, in <module>
    from .colorama import init as colorama_init, Fore, Back, Style
ImportError: No module named 'scripts.colorama'
```

**Comment by mbusb** [comment]
This does not looks like multibootusb issue. This bug report from debian may be related.

**Comment by tkossak** [comment]
Which bug report from debian?

**Comment by mbusb** [comment]
Opps, it is my bad. Follow this link:-
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=665346
