### ISSUE TITLE
Unable to start: Config is not defined

### ISSUE THREAD

**Issue by tonylangworthy** [mbusb/multibootusb#253]
I have tried the latest version, 9.1.0, and I get the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 174, in <module>
    if config.debug is True:
NameError: name 'config' is not defined`

So, I tried an earlier version, 8.9.0, yet I still get the same error, just on a different line:
`Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 164, in <module>
    if config.debug is True:
NameError: name 'config' is not defined`

I am using Ubuntu 16.04 and installed both versions using the install.py script. I originally tried installing using the deb package, but the install failed and I don't have the error now.

**Comment by mbusb** [comment]
Don't install using install.py. Remove the old install and try running
directly from source.

**Comment by tonylangworthy** [comment]
I'm still not able to run it. I'm getting 
`Traceback (most recent call last):
  File "./multibootusb", line 174, in <module>
    if config.debug is True:
NameError: name 'config' is not defined`
when I run ./multibootusb from the root of the source folder.

**Comment by mbusb** [comment]
Did you prefix python3 before multibootusb?

On 15-Jan-2018 6:56 AM, "Tony Langworthy" <notifications@github.com> wrote:

I'm still not able to run it. I'm getting
Traceback (most recent call last): File "./multibootusb", line 174, in
<module> if config.debug is True: NameError: name 'config' is not defined
when I run ./multibootusb from the root of the source folder.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mbusb/multibootusb/issues/253#issuecomment-357560933>,
or mute the thread

**Comment by tonylangworthy** [comment]
I just tried that. Same error, although my version of python is 2.7.12

**Comment by tonylangworthy** [comment]
I do have version 3.5 of python installed on the system and I'm still getting the same error when I run the command with like this:
`python3 ./multibootusb`

**Comment by mbusb** [comment]
What do you see in `/usr/lib/python3/dist-packages/scripts/`? I still believe that you have installed multibootusb in python2.7. You need to remove old install before trying the new method.

**Comment by tonylangworthy** [comment]
I only show 1 directory, __pycache__, in /usr/lib/python3/dist-packages/scripts

**Comment by Tyil** [comment]
I've tried running it from the source directory, and I get the same error:

```
tyil@krata:~/downloads/firefox/multibootusb-9.2.0 » python3 multibootusb -d
Using python version  3.6.1 (default, Dec 31 2017, 01:41:48) 
[GCC 5.4.0] on platform Linux-4.14.12-2-x86_64-Intel-R-_Core-TM-_i7-4700MQ_CPU_@_2.40GHz-with-gentoo-2.2.1
Traceback (most recent call last):
  File "multibootusb", line 170, in <module>
    config.debug = True
NameError: name 'config' is not defined
```

**Comment by shinji-s** [comment]
Try applying the following patch and see if you get more info.
```
diff --git a/multibootusb b/multibootusb
index 0520028..4aaee9c 100644
--- a/multibootusb
+++ b/multibootusb
@@ -34,12 +34,15 @@ try:
     from scripts import gen
     from scripts import config
 except:
+    import traceback
+    traceback.print_exc()
     try:
         from .scripts.mbusb_cli import *
         from .scripts import admin
         from .scripts import gen
         from .scripts import config
     except:
+        traceback.print_exc()
         import scripts

 gui = True
```

**Comment by Tyil** [comment]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks2': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/udisks.py", line 94, in __init__
    '/org/freedesktop/UDisks2')
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks2 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/udisks.py", line 174, in get_udisks
    u = UDisks2()
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/udisks.py", line 97, in __init__
    raise NoUDisks2()
scripts.udisks.NoUDisks2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/udisks.py", line 42, in __init__
    '/org/freedesktop/UDisks'), 'org.freedesktop.UDisks')
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multibootusb", line 32, in <module>
    from scripts.mbusb_cli import *
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/mbusb_cli.py", line 12, in <module>
    from . import usb
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/usb.py", line 20, in <module>
    UDISKS = udisks.get_udisks(ver=None)
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/udisks.py", line 176, in get_udisks
    u = UDisks()
  File "/home/tyil/downloads/firefox/multibootusb-9.2.0/scripts/udisks.py", line 45, in __init__
    raise NoUDisks1()
scripts.udisks.NoUDisks1
Traceback (most recent call last):
  File "multibootusb", line 40, in <module>
    from .scripts.mbusb_cli import *
ModuleNotFoundError: No module named '__main__.scripts'; '__main__' is not a package
Using python version  3.6.1 (default, Dec 31 2017, 01:41:48) 
[GCC 5.4.0] on platform Linux-4.14.12-2-x86_64-Intel-R-_Core-TM-_i7-4700MQ_CPU_@_2.40GHz-with-gentoo-2.2.1
Traceback (most recent call last):
  File "multibootusb", line 190, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```

**Comment by shinji-s** [comment]
What is your host OS and  DE that you are running mbusb under?

**Comment by mbusb** [comment]
Some how the python import is not working for you. Could you please tell us the name of distro?

**Comment by Tyil** [comment]
> What is your host OS
Funtoo GNU+Linux.

> and DE
I seriously doubt this would matter, but it's XMonad.

> Any relevant info in /var/log/{syslog|messages}
No.

> And is the service, either udisks or udisks2 running?
No. `udisks` isn't installed either.

**Comment by shinji-s** [comment]
> No. udisks isn't installed either.

I think this is the cause of the error since mbusb uses udisksd through dbus to mount the target usb device and the interface is probed during module loading by the following statement
> UDISKS = udisks.get_udisks(ver=None)

in scripts/usb.py. Will you enable either of the udisks services, preferably udisks2,  and see if the problem goes away though setup may not be trivial? (https://wiki.gentoo.org/wiki/Udisks)

**Comment by Tyil** [comment]
> I think this is the cause of the error since mbusb uses udisksd through dbus to mount the target usb device and the interface is probed during module loading by the following statement

This is [not mentioned as a dependency](http://multibootusb.org/page_faq/#your-package-for-my-favourite-distro-never-worked-for-me-what-can-i-do-now). Additionally, the supposed error reporting is very LTA.

I was originally looking for something small and simple to accomplish a reasonable task, but now it seems this project isn't the solution for me.

**Comment by thedogb** [comment]
is this problem solved? i meet this problem too.

**Comment by twilbers** [comment]
I also get this error when I install from source on Arch Linux (Linux-4.16.5-1-ARCH-x86_64-with-arch WM i3 and Python 3.6.5-2 ) .

`sudo multibootusb` and `sudo python3 /bin/multibootusb` result in:
```
Using python version  3.6.5 (default, Apr 14 201I also get this error when I install from source on Arch Linux (Linux-4.16.5-1-ARCH-x86_64-with-arch & Python 3.6.5-2 ) .

`sudo multibootusb` and `sudo python3 /bin/multibootusb` result in:
```
Using python version  3.6.5 (default, Apr 14 2018, 13:17:30) 
[GCC 7.3.1 20180406] on platform Linux-4.16.5-1-ARCH-x86_64-with-arch
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```

`pacman -Q| grep py`

```
pyalpm 0.8.2-2
pygobject-devel 3.28.2-1
pygobject2-devel 2.28.7-1
pygtk 2.24.0-8
pyqt5-common 5.10.1-2
python 3.6.5-2
python-appdirs 1.4.3-1
python-chardet 3.0.4-1
python-dbus 1.2.6-1
python-dbus-common 1.2.6-1
python-decorator 4.3.0-1
python-gobject 3.28.2-1
python-idna 2.6-1
python-packaging 16.8-2
python-pyparsing 2.2.0-1
python-pyqt5 5.10.1-2
python-pyudev 0.21.0-2
python-regex 2018.02.21-1
python-requests 2.18.4-1
python-setuptools 1:39.1.0-1
python-sip 4.19.8-1
python-six 1.11.0-1
python-slip 0.6.5-1
python-urllib3 1.22-1
python2 2.7.14-3
python2-appdirs 1.4.3-1
python2-cairo 1.17.0-1
python2-chardet 3.0.4-1
python2-gobject 3.28.2-1
python2-gobject2 2.28.7-1
python2-idna 2.6-1
python2-ipaddr 2.1.11-1
python2-packaging 16.8-2
python2-pyparsing 2.2.0-1
python2-requests 2.18.4-1
python2-setuptools 1:39.1.0-1
python2-six 1.11.0-1
python2-urllib3 1.22-1
```

`pip freeze`

```
appdirs==1.4.3
aurman==2.9.24
chardet==3.0.4
decorator==4.3.0
enum-compat==0.0.2
i3ipc==1.5.1
idna==2.6
multibootusb==9.2.0
packaging==16.8
pip-autoremove==0.9.0
pipdeptree==0.12.1
pyalpm==0.8
pygobject==3.28.2
pyparsing==2.2.0
pyudev==0.21.0.dev20161225
ranger-fm==1.9.1
regex==2018.2.21
requests==2.18.4
shadowsocks==2.9.1
six==1.11.0
slip==0.6.5
slip.dbus==0.6.5
team==1.0
urllib3==1.22
```8, 13:17:30) 
[GCC 7.3.1 20180406] on platform Linux-4.16.5-1-ARCH-x86_64-with-arch
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```

`pacman -Q| grep py`

```
pyalpm 0.8.2-2
pygobject-devel 3.28.2-1
pygobject2-devel 2.28.7-1
pygtk 2.24.0-8
pyqt5-common 5.10.1-2
python 3.6.5-2
python-appdirs 1.4.3-1
python-chardet 3.0.4-1
python-dbus 1.2.6-1
python-dbus-common 1.2.6-1
python-decorator 4.3.0-1
python-gobject 3.28.2-1
python-idna 2.6-1
python-packaging 16.8-2
python-pyparsing 2.2.0-1
python-pyqt5 5.10.1-2
python-pyudev 0.21.0-2
python-regex 2018.02.21-1
python-requests 2.18.4-1
python-setuptools 1:39.1.0-1
python-sip 4.19.8-1
python-six 1.11.0-1
python-slip 0.6.5-1
python-urllib3 1.22-1
python2 2.7.14-3
python2-appdirs 1.4.3-1
python2-cairo 1.17.0-1
python2-chardet 3.0.4-1
python2-gobject 3.28.2-1
python2-gobject2 2.28.7-1
python2-idna 2.6-1
python2-ipaddr 2.1.11-1
python2-packaging 16.8-2
python2-pyparsing 2.2.0-1
python2-requests 2.18.4-1
python2-setuptools 1:39.1.0-1
python2-six 1.11.0-1
python2-urllib3 1.22-1
```

`pip freeze`

```
appdirs==1.4.3
aurman==2.9.24
chardet==3.0.4
decorator==4.3.0
enum-compat==0.0.2
i3ipc==1.5.1
idna==2.6
multibootusb==9.2.0
packaging==16.8
pip-autoremove==0.9.0
pipdeptree==0.12.1
pyalpm==0.8
pygobject==3.28.2
pyparsing==2.2.0
pyudev==0.21.0.dev20161225
ranger-fm==1.9.1
regex==2018.2.21
requests==2.18.4
shadowsocks==2.9.1
six==1.11.0
slip==0.6.5
slip.dbus==0.6.5
team==1.0
urllib3==1.22
```

**Comment by shinji-s** [comment]
Please apply the patch shown above or use devel branch on github and examine the traceback.
If you get the same traceback as shown above, you'll have to tweak OS configuration
so that disks can be mounted/umounted by udisks/udisks2 daemon through dbus interface.
I don't know yet exact configuration steps you should take though. It seems udisk/disks2 is enabled
by default in many distros.

**Comment by twilbers** [comment]
Thanks for the help! I ran: 
`git clone https://github.com/mbusb/multibootusb`
`cd multibootusb`
`git branch devel`
`git checkout devel`
`sudo python3 install.py`
`sudo multibootusb`

However it still outputs: 
```
Using python version  3.6.5 (default, Apr 14 2018, 13:17:30) 
[GCC 7.3.1 20180406] on platform Linux-4.16.5-1-ARCH-x86_64-with-arch
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```
Let me know if i missed a step. It looks like my Arch install did not have udisk2 installed. I installed it and started the daemon, but alas i am getting the same error.

**Comment by mbusb** [comment]
Please don't install. Remove the install and execute run directly from
source and check if the issue persist.

**Comment by shinji-s** [comment]
Please verify that ImportError is caught at the beginning of multibootusb script.
Then
> sudo multibootusb

does
> sudo ./multibootusb

or

> sudo python3 multibootusb


make difference?
(Even if either of these works, you are still advised to remove previous installations.)

**Comment by Tyil** [comment]
@shinji-s which "many distros" are you talking about? It's not enabled in any of the OSs I'm using, which include Funtoo, Archlinux, Ubuntu and FreeBSD.

**Comment by shinji-s** [comment]
Judging from the amount of issues raised about mbusb not starting and of those about unexpected behavior after it has started, it seems to me that many distros have udisks enabled. I'm running mbusb on Ubuntu 16.04.4 and debian 9 without explicitly installing/enabling udisks. According the author, neither Fedora or Suse in addition to a debian did not exhibit the problem.

**Comment by Tyil** [comment]
I just double-checked my (only) Ubuntu box, which is at 16.04.4, and it does not contain udisks. It feels like it just gets pulled in as a dependency for many people, but is not enabled as a default.

It's also not referred to in the documentation about dependencies, which it should, no matter if it's a default on some rare distros or not. Additionally, the error it shows is unrelated to what is actually amiss and seems to bring more confusion than actually aiding the user to solve it.

**Comment by shinji-s** [comment]
> It feels like it just gets pulled in as a dependency for many people, but is not enabled as a default.

That is likely. I'll check next time I have chance to do clean installation.

> Additionally, the error it shows is unrelated to what is actually amiss and seems to bring more confusion than actually aiding the user to solve it.

A valid criticism.  I appreciate if you try devel branch and see if https://github.com/mbusb/multibootusb/pull/358 correctly address your concern.

**Comment by Tyil** [comment]
Using the `devel` branch, the output is as follows:

```
Using python version  3.6.1 (default, Apr 29 2018, 13:52:48) 
[GCC 5.4.0] on platform Linux-4.14.12-2-x86_64-Intel-R-_Core-TM-_i7-4700MQ_CPU_@_2.40GHz-with-gentoo-2.2.2
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks2': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tyil/downloads/firefox/multibootusb/scripts/udisks.py", line 91, in __init__
    '/org/freedesktop/UDisks2')
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks2 was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tyil/downloads/firefox/multibootusb/scripts/udisks.py", line 167, in get_udisks
    u = UDisks2()
  File "/home/tyil/downloads/firefox/multibootusb/scripts/udisks.py", line 94, in __init__
    raise NoUDisks2()
scripts.udisks.NoUDisks2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.UDisks': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tyil/downloads/firefox/multibootusb/scripts/udisks.py", line 42, in __init__
    '/org/freedesktop/UDisks'), 'org.freedesktop.UDisks')
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multibootusb", line 32, in <module>
    from scripts.mbusb_cli import *
  File "/home/tyil/downloads/firefox/multibootusb/scripts/mbusb_cli.py", line 12, in <module>
    from . import usb
  File "/home/tyil/downloads/firefox/multibootusb/scripts/usb.py", line 25, in <module>
    UDISKS = udisks.get_udisks(ver=None)
  File "/home/tyil/downloads/firefox/multibootusb/scripts/udisks.py", line 169, in get_udisks
    u = UDisks()
  File "/home/tyil/downloads/firefox/multibootusb/scripts/udisks.py", line 45, in __init__
    raise NoUDisks1()
scripts.udisks.NoUDisks1
```

**Comment by shinji-s** [comment]
Thank you for trying. It appears the patch is working as expected.

apt-cache rdepends udisks2 shows a lot of packages. I'll see which one(s) of them I have installed.

**Comment by shinji-s** [comment]
ubuntu-desktop recommends => gnome-disk-utility dpends on => gnome-udisks2
So installing ubuntu-desktop pulls in udisks2, does not it?

```
root@K553:~# apt-cache rdepends udisks2 | egrep "^  [a-z]" | awk '{$1=$1;print}' | LANG=C xargs dpkg -l
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
rc  dbus-user-sess 1.10.6-1ubun all          simple interprocess messaging sys
ii  gnome-disk-uti 3.18.3.1-1ub amd64        manage and configure disk drives 
ii  gparted        0.25.0-1     amd64        GNOME partition editor
ii  gvfs-daemons   1.28.2-1ubun amd64        userspace virtual filesystem - se
ii  python3-checkb 0.22-1       all          collection of Python modules used
ii  usb-creator-co 0.3.2        amd64        create a startup disk using a CD 
dpkg-query: no packages found matching cockpit-storaged
... rest deleted

```

**Comment by mbusb** [comment]
@Patrick Spek
Could you tell me the way you have installed multibootusb? Is it using the
install script provided with multibootusb or binaries like deb / rpm?

**Comment by twilbers** [comment]
I ran from source but having the same issue as before (`NameError: name 'config' is not defined`):

`git clone https://github.com/mbusb/multibootusb`
`cd multibootusb`
`git branch devel`
`git checkout devel`
Change release and pyinstall directory (/usr/bin/pyinstall)
`sudo python3 build_pkg run`

**Comment by shinji-s** [comment]
> git branch devel

will create a new local branch that starts at master/HEAD.
To fix your local repo do
>git checkout master
>git branch -D devel
>git checkout devel

To reduce complexity, please run straight from the source with the command below instead of running build_pkg.
>sudo python3 multibootusb

**Comment by twilbers** [comment]
Thanks for helping  my with _my_ error. No error with devel branch for me, now. When i install dependencies manually, and run source. I tried both with and without udisks2 installed an daemon running. And did not receive an error. Is it necessary or best to keep udisks?

**Comment by Tyil** [comment]
> So installing ubuntu-desktop pulls in udisks2, does not it?

Presumably, but not every Ubuntu machine has that installed. In fact, you can select a minimal install from the GUI based installer last I heard, which would not include `ubuntu-desktop`.

> Could you tell me the way you have installed multibootusb?

It is not installed to the system, I'm running it from the cloned repository.

**Comment by twilbers** [comment]
Although the GUI launches. I am getting a error when I select a partition, select a ISO ([Arch Linux ISO] (http://mirrors.acm.wpi.edu/archlinux/iso/2018.05.01/archlinux-2018.05.01-x86_64.iso)) and hit "Install disto" I get the following traceback:

```

Persistence support is not available for archlinux-2018.04.01-x86_64.iso
QXcbConnection: XCB error: 3 (BadWindow), sequence: 889, resource id: 4194767, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/home/gavagai/tmp/multibootusb/scripts/mbusb_gui.py", line 559, in onCreateClick
    installing = self.onCreateClick_impl()
  File "/home/gavagai/tmp/multibootusb/scripts/mbusb_gui.py", line 620, in onCreateClick_impl
    if not self.check_remount():
  File "/home/gavagai/tmp/multibootusb/scripts/mbusb_gui.py", line 804, in check_remount
    self.update_usb_mount) as m:
  File "/home/gavagai/tmp/multibootusb/scripts/usb.py", line 464, in __enter__
    self.assert_no_access()
  File "/home/gavagai/tmp/multibootusb/scripts/usb.py", line 454, in assert_no_access
    stdin=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lsof': 'lsof'
Aborted
```

Feel free to (re)move if this issue is not related, unfortunately i cannot tell.

**Comment by shinji-s** [comment]
Sorry, please install 'lsof' as well. That command is used determine if a target usb device can be unmounted.
@mbusb, please remember to update dependency description before cutting a new release.

**Comment by shinji-s** [comment]
Presently it is my understanding that mbusb does not work without udisks.
I suggest to keep the package installed.

> I tried both with and without udisks2 installed an daemon running (both no error).

Would it be possible that you uninstalled the package but the daemon was still running?

**Comment by twilbers** [comment]
> Would it be possible that you uninstalled the package but the daemon was still running?

It is possible. I think I also spoke too soon and after launching the GUI it eventually gave an error without udisks anyway.

> Sorry, please install 'lsof' as well. That command is used determine if a target usb device can be unmounted.

Great that error goes away after lsof installs but now i get:

```
Traceback (most recent call last):
  File "/home/gavagai/tmp/multibootusb/scripts/mbusb_gui.py", line 361, in install_syslinux
    syslinux_default(config.usb_disk)
  File "/home/gavagai/tmp/multibootusb/scripts/syslinux.py", line 170, in syslinux_default
    r = linux_install_default_bootsector(usb_disk, mbr_install_cmd)
  File "/home/gavagai/tmp/multibootusb/scripts/syslinux.py", line 99, in linux_install_default_bootsector
    subprocess.call('chmod +x ' + syslinux_path)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chmod +x /root/.multibootusb/syslinux/bin/syslinux4': 'chmod +x /root/.multibootusb/syslinux/bin/syslinux4'
Aborted
```

**Comment by twilbers** [comment]
> It appears to occur first time you use devel branch. I had the same issue
but gone after using it for second time. But it is a bug.

It seems to do it every time for me. That is every time I unmount, remake the file system, and try to install distro it aborts with:

```
FileNotFoundError: [Errno 2] No such file or directory: 'chmod +x /root/.multibootusb/syslinux/bin/syslinux4': 'chmod +x /root/.multibootusb/syslinux/bin/syslinux4'
```

**Comment by shinji-s** [comment]
Very sorry, this is my bonehead mistake. Please apply the patch below or wait for awhile until the fix arrives to the branch and then perform "git pull".
```
diff --git a/scripts/syslinux.py b/scripts/syslinux.py
index 1ffa0f2..b3eb639 100644
--- a/scripts/syslinux.py
+++ b/scripts/syslinux.py
@@ -96,7 +96,7 @@ def linux_install_default_bootsector(usb_disk, mbr_install_cmd):
     with usb.UnmountedContext(usb_disk, config.update_usb_mount):
         syslinux_cmd = [syslinux_path, '-i', '-d', 'multibootusb', usb_disk]
         if os.access(syslinux_path, os.X_OK) is False:
-            subprocess.call('chmod +x ' + syslinux_path)
+            subprocess.call('chmod +x ' + syslinux_path, shell=True)
         log("\nExecuting ==> %s\n" % syslinux_cmd)
         config.status_text = 'Installing default syslinux version 4...'
         if subprocess.call(syslinux_cmd) == 0:

```

**Comment by shinji-s** [comment]
Now the fix (https://github.com/mbusb/multibootusb/pull/363) is in the branch.

**Comment by XanthusL** [comment]
Arch Linux, Gnome3, multibootusb-9.2.0-1, 
```sh
%multibootusb   
Using python version  3.7.0 (default, Sep 15 2018, 19:13:07) 
[GCC 8.2.1 20180831] on platform Linux-4.18.14-arch1-1-ARCH-x86_64-with-arch
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined

```

**Comment by m1ndk** [comment]
udisks should be in the dependencies tree as already suggested but still not updated (multibootusb 9.2.0-2) I get all the errors mentioned above, no point in pasting them I believe.

**Comment by zack-emmert** [comment]
AUR Package maintainer here.

In my case, I get the same error as @XanthusL even if extra/udisks2 is installed. I can't really push any fixes until I know what needs to be done to fix it.

**Comment by hhlp** [comment]
same error here in :fedora: 30 download from binary... http://multibootusb.org/page_download/

 multibootusb           noarch          9.2.0-1                @commandline          7.6 M

```
Using python version  3.7.3 (default, May 11 2019, 00:38:04)                               
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on platform Linux-5.0.14-300.fc30.x86_64-x86_64-with
-fedora-30-Thirty                                                                          
Traceback (most recent call last):                                                         
  File "/usr/local/bin/multibootusb", line 187, in <module>                                
    if config.debug is True:                                                               
NameError: name 'config' is not defined    
```

**Comment by fsociety29a** [comment]
Another Arch AUR package user. The patches offered here won't work.

**Comment by fobriste** [comment]
I also get this error if I forget to run with sudo, if that helps anyone.

**Comment by j00ch** [comment]
I also run into this error, when i remove the config.debug lines from multibootusb i get:
`File "/usr/bin/multibootusb", line 210, in <module>
    running_from()
  File "/usr/bin/multibootusb", line 53, in running_from
    gen.log('Using python version ' + python_version + 'on platform ' + _platform, _print=False)
NameError: name 'gen' is not defined'

**Comment by Soundtoxin** [comment]
I just ran into this issue installing the package from the Void repos.
