### ISSUE TITLE
Error when installing Distro (read only file system) 

### ISSUE THREAD

**Issue by fabito** [mbusb/multibootusb#31]
Every distro I try to install I keep getting the following error during the syslinux config file update:

```
RRIP: rrip_offset 0
ISO passed.
Distro detected is ubuntu
Persistence option is available.
Closing the persistence size chooser window.
Persistence choosen is 0 MB
RRIP: rrip_offset 0RRIP: rrip_offset 0

Install dir is /media/fabio/multibootus/multibootusb/xubuntu-15.10-desktop-amd64
Distro extraction completed...
RRIP: rrip_offset 0


Found syslinux version 6


distro_syslinux_install_dir is /multibootusb/xubuntu-15.10-desktop-amd64/isolinux
distro_sys_install_bs is /media/fabio/multibootus/multibootusb/xubuntu-15.10-desktop-amd64/isolinux/ubuntu.bs
Executing ==> /home/fabio/.multibootusb/syslinux/bin/syslinux6 -i -d /multibootusb/xubuntu-15.10-desktop-amd64/isolinux /dev/sdb1

Syslinux install on distro directory is success...

Executing ==> dd if=/dev/sdb1 of=/media/fabio/multibootus/multibootusb/xubuntu-15.10-desktop-amd64/isolinux/ubuntu.bs count=1

1+0 records in
1+0 records out
512 bytes (512 B) copied, 0,0983977 s, 5,2 kB/s

Bootsector copy is success...
RRIP: rrip_offset 0
Executing ==> /home/fabio/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sdb1
Default syslinux install is success...
1+0 records in
1+0 records out
440 bytes (440 B) copied, 0,000239348 s, 1,8 MB/s
mbr install is success...
Checking boot flag on /dev/sdb
Disk already has boot flag.
RRIP: rrip_offset 0
Applying Ubuntu patch...
Copying chain.c32
Copying gfxboot.c32
Copying ldlinux.c32
Could not copy ldlinux.c32
Could not copy libcom32.c32
Could not copy libutil.c32
Could not copy vesamenu.c32
RRIP: rrip_offset 0
Updating main syslinux config file...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 298, in install_syslinux
    self.update_cfg_files.distro_cfg_files()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 171, in distro_cfg_files
    self.main_cfg_file()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 203, in main_cfg_file
    config_file = open(sys_cfg_file, "a")
IOError: [Errno 30] Read-only file system: '/media/fabio/multibootus/multibootusb/syslinux.cfg'
```

**Comment by alcir** [comment]
Same problem here

**Comment by Yanpas** [comment]
I have the same issue with Linux Mint #40 .
There is alternative http://www.pendrivelinux.com/yumi-multiboot-usb-creator/ , disrtos are installed succesfully there, but currently there is no linux version

**Comment by mbusb** [comment]
Try latest source. It has fixed this issue.
