### ISSUE TITLE
Unable to start second time

### ISSUE THREAD

**Issue by Yanpas** [mbusb/multibootusb#34]
First run of multibootusb was successful. then (as far as i remeber) it crashed. Now I am able to start it only as root. If I run it as normal user I face this :
```
multibootusb 
/usr/bin/sudo
[sudo] password for yanpas: Using PyUdev for detecting USB drives...
/dev/sdd1
df: «/root/.gvfs»: Отказано в доступе
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 667, in <module>
    window = AppGui()
  File "/usr/bin/multibootusb", line 110, in __init__
    self.add_device()
  File "/usr/bin/multibootusb", line 123, in add_device
    self.onComboChange()
  File "/usr/bin/multibootusb", line 157, in onComboChange
    df_out = subprocess.check_output("df", shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'df' returned non-zero exit status 1
```
Linux Mint 17.2  64 bit Kernel 3.16

**Comment by mbusb** [comment]
Fixed.
