### ISSUE TITLE
Detects partition but does not recognize it/permit install of distro

### ISSUE THREAD

**Issue by orgelspielerkmd** [mbusb/multibootusb#387]
I opened the program with the pkexec multibootusb command in the terminal, which opened the GUI interface.

I selected the dev/sdc1 partition of a 32GB Sandisk USB drive I have and received the following response (below).  By recognize, I mean that the info under USB details does not change from the  drive that was selected when the GUI opened.  After that, I can attempt to Install distro with an .iso file, but then more errors occur (below after divider).

Selected device /dev/sdc1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 481, in details
    details = details_udev(usb_disk_part)
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 269, in details_udev
    mount_point = UDISKS.mount(usb_disk_part) or ""
  File "/usr/lib/python3/dist-packages/scripts/udisks.py", line 145, in mount
    dbus_interface=self.FILESYSTEM))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object

------------------------------------
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 149, in onComboChange
    config.usb_details = usb.details(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 483, in details
    details = details_udisks2(usb_disk_part)
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 324, in details_udisks2
    mount_point = bd.Get('org.freedesktop.UDisks2.Filesystem', 'MountPoints', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.UDisks2.Filesystem'
Executing ==> 7z -ssc-  x -y "/home/chris/linuxmint-18.3-xfce-32bit.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/chris/linuxmint-18.3-xfce-32bit.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/chris/linuxmint-18.3-xfce-32bit.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/chris/linuxmint-18.3-xfce-32bit.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
Persistence option is available.
Persistence Max Size: Unknown

**Comment by shinji-s** [comment]
Can you mount the partition ouside of multibootusb?
What do you get if you run 'sudo parted /dev/sdc print'?
