### ISSUE TITLE
python3-multibootusb_9.2.0-1_all.deb: Missing files?

### ISSUE THREAD

**Issue by m-ueberall** [mbusb/multibootusb#390]
I installed the current Debian/Ubuntu package on Ubuntu Xenial (16.04), but it looks as if something is missing (and the first message below should be suppressed or replaced by one signalling whether /sbin/gdisk is installed or not, I guess):
```
[GCC 5.4.0 20160609] on platform Linux-4.15.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
Could not find resource 'data/tools/gdisk/gdisk.exe'.
[...]
Using gptmbr.bin for mbr install.
Could not find resource 'data/tools/gptmbr.bin'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 349, in install_syslinux
    syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 107, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: Can't convert 'NoneType' object to str implicitly
```
(The device in question was identified as a GPT disk, and install hangs at this point. A previous run against a MBR disk finished, but it was not possible to boot from that one.)

**Comment by m-ueberall** [comment]
The above is a duplicate of issue #361
