### ISSUE TITLE
Pytthon type conversion error while installing ISO

### ISSUE THREAD

**Issue by unixbhaskar** [mbusb/multibootusb#397]
System : Linux debian 4.17.3-debian #1 SMP Tue Jun 26 12:04:36 IST 2018 x86_64 GNU/Linux

`
root@debian_10:11:19_Wed Jun 27:/data/ISO#/usr/bin/python3 /usr/bin/multibootusb -c -i archlinux-2018.06.01-x86_64.iso -t /dev/sdb1
Using python version  3.6.6rc1 (default, Jun 13 2018, 06:59:48) 
[GCC 8.1.0] on platform Linux-4.17.3-debian-x86_64-with-debian-buster-sid
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb from Command line...
25008
True
Device /dev/sdb1 is a GPT disk...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 212, in <module>
    cli_install_distro()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_cli.py", line 66, in cli_install_distro
    iso_install(config.image_path)
  File "/usr/lib/python3/dist-packages/scripts/mbusb_cli.py", line 84, in iso_install
    elif size_not_enough(iso_image, config.usb_disk) is True:
  File "/usr/lib/python3/dist-packages/scripts/gen.py", line 307, in size_not_enough
    return bool(isoSize > usb_size)
TypeError: '>' not supported between instances of 'int' and 'str'
`

**Comment by alandmoore** [comment]
Core issue here is that usb.details *might* return a number, or *might* return a string, depending on the scenario and the backend used.  For example, details_udisks2 populates the size values with "No Mount" when there is no filesystem mounted at the mount point, while details_udev returns an empty string.

I see a few possible ways to fix this:

- Quick'n'dirty:  `try` to cast the size value to a string in gen.py, set to 0 if it isn't castable.
- Slightly better: Set the size values to zero in the details_* backends when a device isn't mounted.  Make sure each function only returns number types for size values.
- Probably best:  Throw an exception in the details functions when the device isn't mounted.  Make sure all calling code handles these exceptions.

Any core contributors have a preference on which approach they'd like to see?

**Comment by shinji-s** [comment]
+1 on the third.

**Comment by alandmoore** [comment]
I have code in this branch: https://github.com/alandmoore/multibootusb/tree/fixes_397  that addresses the changes in `usb.py`, but any code calling `usb.details()` is going to need to potentially catch an exception and handle it appropriately.

Before I make all those changes, I was hoping someone could look at that change and decide if this is the direction you want to go with this.

**Comment by mbusb** [comment]
Looks good. Could you make additional changes to catch the `PartitionNotMounted` exception and make pull request.

**Comment by alandmoore** [comment]
I'll start digging into it.

**Comment by alandmoore** [comment]
Kind of off-topic, but is there a reason why mbusb_gui.py uses tabs instead of spaces?  It's not a huge deal, but it's at odds with the rest of the project and I have to swap a lot of editor settings every time I work on it.
Would it be OK to swap this over to spaces?
