### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 7201: invalid start byte

### ISSUE THREAD

**Issue by jpereira** [mbusb/multibootusb#403]
Below can be seen more information about the issue.

```
# dpkg -s python3-multibootusb | grep Version
Version: 9.2.0-1
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
# 
# sudo fdisk -l /dev/sdb
Disk /dev/sdb: 29,7 GiB, 31914983424 bytes, 62333952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00ba0fca

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1  *     2048 62332927 62330880 29,7G 83 Linux
#
```

I have tried to create a bootable usb driver using the below *.iso images.

```
# md5sum *.iso
9f4b36a37e7d0e2ad16515204d842a81  macOSsierra.iso
129292a182136a35e1f89c586dbac2e2  ubuntu-18.04-desktop-amd64.iso
#
```

The crash.

1. Can't install the previous ISO images.

```
# sudo multibootusb -c -y -i /home/jpereira/Downloads/macOSsierra.iso,/home/jpereira/Downloads/ubuntu-18.04-desktop-amd64.iso -t /dev/sdb1 2>&1 
Using python version  3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on platform Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb from Command line...
25008
True
/media/root/f49bf30d-376e-45a9-a251-db56e2233c43
Device /dev/sdb1 is a MBR disk...
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Executing ==> 7z -ssc-  x -y "/home/jpereira/Downloads/macOSsierra.iso" -o"/home/jpereira/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/jpereira/Downloads/macOSsierra.iso" -o"/home/jpereira/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/jpereira/Downloads/macOSsierra.iso" -o"/home/jpereira/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/jpereira/Downloads/macOSsierra.iso" -o"/home/jpereira/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
Initiating installation process for macOSsierra
Detected distro type is    :slitaz

Selected ISO is          :"macOSsierra.iso"
Selected target device is  :"/dev/sdb1"
Skipping user confirmation for /home/jpereira/Downloads/macOSsierra.iso
Copying multibootusb directory to /media/root/f49bf30d-376e-45a9-a251-db56e2233c43
EFI/BOOT directory does not exist. Creating new.
Copying EFI directory to /media/root/f49bf30d-376e-45a9-a251-db56e2233c43
Installing macOSsierra.iso on /media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra                                                                                                                         |
Executing ==> 7z -ssc-  x -y -o"/media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra" "/home/jpereira/Downloads/macOSsierra.iso" 2> /dev/null
ISO extracted successfully. Sync is in progress...##################################################################################################################################                                            |
Distro does not use isolinux for booting ISO.
Using mbr.bin msdos mbr install.

Executing ==> /home/jpereira/.multibootusb/syslinux/bin/extlinux4 --install /media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb
/media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb is device /dev/sdb1

Default Extlinux install is success...


Executing ==> dd bs=440 count=1 conv=notrunc if=/usr/share/multibootusb/data/tools/mbr.bin of=/dev/sdb
1+0 records in
1+0 records out
440 bytes copied, 0,00487379 s, 90,3 kB/s

mbr install is success...


Checking boot flag on /dev/sdb

Disk /dev/sdb already has boot flag.

Updating distro specific config files...
In '/media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra/OS X Base System/System/Library/Sandbox/rootless.conf', following paths are used as they are though they don't exist.
  /Applications/App
  /Applications/Automator.app
  /Applications/Calculator.app
  /Applications/Calendar.app
  /Applications/Chess.app
  /Applications/Contacts.app
  /Applications/Dashboard.app
  /Applications/Dictionary.app
  /Applications/DVD
  /Applications/FaceTime.app
  /Applications/Font
  /Applications/Game
  /Applications/Image
  /Applications/Launchpad.app
  /Applications/Mail.app
  /Applications/Maps.app
  /Applications/Messages.app
  /Applications/Mission
  /Applications/Notes.app
  /Applications/Photo
  /Applications/Photos.app
  /Applications/Preview.app
  /Applications/QuickTime
  /Applications/Reminders.app
  /Applications/Safari.app
  /Applications/Siri.app
  /Applications/Stickies.app
  /Applications/System
  /Applications/TextEdit.app
  /Applications/Time
  /Applications/Utilities/Activity
  /Applications/Utilities/AirPort
  /Applications/Utilities/Audio
  /Applications/Utilities/Bluetooth
  /Applications/Utilities/Boot
  /Applications/Utilities/ColorSync
  /Applications/Utilities/Console.app
  /Applications/Utilities/Digital
  /Applications/Utilities/Disk
  /Applications/Utilities/Feedback
  /Applications/Utilities/Grab.app
  /Applications/Utilities/Grapher.app
  /Applications/Utilities/Keychain
  /Applications/Utilities/Migration
  /Applications/Utilities/Script
  /Applications/Utilities/System
  /Applications/Utilities/Terminal.app
  /Applications/Utilities/VoiceOver
  /Library/Application
  /Library/Filesystems/NetFSPlugins/Staged
  /Library/Filesystems/NetFSPlugins/Valid
  /Library/Preferences/SystemConfiguration/com.apple.Boot.plist
  /System
  /System/Library/Assets
  /System/Library/Caches
  /System/Library/Extensions
  /System/Library/Extensions/
  /System/Library/LaunchDaemons/com.apple.UpdateSettings.plist
  /System/Library/PreinstalledAssets
  /System/Library/Speech
  /System/Library/User
  /bin
  /private/var/db/datadetectors
  /private/var/db/dyld
  /private/var/folders
  /sbin
  /usr
  /usr/libexec/cups
  /usr/local
  /usr/share/man
  /usr/share/snmp
  /etc
  /tmp
  /var
In '/media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra/OS X Base System/private/etc/asl.conf', '/var/log/asl/Logs/aslmanager' is kept as is though it does not exist.
Applied a rewrite exception on '/media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra/OS X Base System/private/etc/asl.conf' as shown below:
  /var/log/system.log is kept as is. [1]
Applied a rewrite exception on '/media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra/OS X Base System/private/etc/syslog.conf' as shown below:
  /etc/asl.conf is kept as is. [1]
In '/media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra/OS X Base System/private/etc/notify.conf', following paths are used as they are though they don't exist.
  /etc/localtime
  /etc/hosts
  /etc/services
  /etc/protocols
Updating multibootusb config file...
Trying to create loopback.cfg
loopback.cfg file is set to /media/root/f49bf30d-376e-45a9-a251-db56e2233c43/multibootusb/macOSsierra/loopback.cfg
Failed to convert syslinux config file to loopback.cfg
Using loopback.cfg to boot this distro.
Updating grub.cfg file...
size of the ISO is 7.2G
Updated entry in grub.cfg...
Probing 'chitab.txt'!
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 212, in <module>
    cli_install_distro()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_cli.py", line 71, in cli_install_distro
    iso_install(config.image_path)
  File "/usr/lib/python3/dist-packages/scripts/mbusb_cli.py", line 112, in iso_install
    config.persistence)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 402, in update_distro_cfg_files
    callback(dirpath, f)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 374, in fix_desktop_image_in_thema_callback
    for line in f.readlines():
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1933: invalid start byte
# 

```

2. Can't use the debug `-d` option.

```
# sudo multibootusb -c -y -i /home/jpereira/Downloads/macOSsierra.iso,/home/jpereira/Downloads/ubuntu-18.04-desktop-amd64.iso -t /dev/sdb1 -d 2>&1 
Using python version  3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on platform Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 6, in <module>
    from colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 188, in <module>
    from scripts.debug import colors
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 11, in <module>
    raise e
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 9, in <module>
    from .colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'scripts.colorama'
#
```

ps: perhaps add some try..catch friendly message showing the missing coloram module.

**Comment by shinji-s** [comment]
Commit https://github.com/mbusb/multibootusb/commit/266039675edfdd761bc5fb95ba03bb9d87139d77 should have fixed the first issue but it seems the source code shown in the traceback does not contain this patch though the log output says "Running multibootusb version 9.2.0 from installed system...".
@mbusb any ideas?

**Comment by shinji-s** [comment]
I checked the deb package file on www.multibootusb.org and it contains update_cfg_file.py without the commit. Since the merge was on the day of the release, I guess the commit was merged after the package was created and then the release tag got attached.
So the next release would fix the first issue.

**Comment by olih10200** [comment]
Hi,

On Debian 9:
Linux d9 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
Just downloaded/installed .deb:
python3-multibootusb_9.2.0-1_all.deb

Adding deb-9-netinst (LM19 installed before successfully) gave me:
```
Updating distro specific config files...
In '/media/root/89DB-D02F/multibootusb/debian-9.4.0-amd64-netinst/boot/grub/grub.cfg', '/isolinux/splash.png;' is kept as is though it does not exist.
Applied 2 rewrite exceptions on '/media/root/89DB-D02F/multibootusb/debian-9.4.0-amd64-netinst/install.amd/xen/debian.cfg' as shown below:
  /usr/share/doc/xen-utils-common/examples is kept as is. [1]
  /home/bozo/.Xauthority is kept as is. [1]
Updating multibootusb config file...
Using boot/grub/x86_64-efi/grub.cfg to boot this distro.
Updating grub.cfg file...
size of the ISO is 291.0M
Updated entry in grub.cfg...
Probing 'README.mirrors.txt'!
Probing 'README.txt'!
Probing 'md5sum.txt'!
Probing 'bug-log-access.txt'!
Probing 'bug-log-mailserver.txt'!
Probing 'bug-mailserver-refcard.txt'!
Probing 'bug-maint-info.txt'!
Probing 'bug-maint-mailcontrol.txt'!
Probing 'bug-reporting.txt'!
Probing 'constitution.txt'!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 352, in install_syslinux
    config.distro, config.persistence)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 402, in update_distro_cfg_files
    callback(dirpath, f)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 374, in fix_desktop_image_in_thema_callback
    for line in f.readlines():
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 3408: invalid start byte
Félbeszakítva
```

**Comment by Palando** [comment]
I have the same problem in OpenSUSE Tumbleweed when I try to add Debian.

**Comment by KentBrockman** [comment]
Also having this issue when installing debian-10.2.0

System details:
```
> dpkg -s python3-multibootusb | grep Version
Version: 9.2.0-1
> uname -a
Linux phoenix 5.3.0-7625-generic #27~1576774560~19.10~f432cd8-Ubuntu SMP Thu Dec 19 20:35:37 UTC  x86_64 x86_64 x86_64 GNU/Linux
> sudo fdisk -l /dev/sda
Disk /dev/sda: 28.92 GiB, 31029460992 bytes, 60604416 sectors
Disk model: DataTraveler 3.0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: B7365DAC-89DB-4D0C-8994-45E0AB0B1CB4

Device      Start      End  Sectors  Size Type
/dev/sda1  102400 60602367 60499968 28.9G Microsoft basic data
```

Running the operation from the UI:
```
> sudo multibootusb-pkexec
Using python version  3.7.5 (default, Nov 20 2019, 09:21:52)
[GCC 9.2.1 20191008] on platform Linux-5.3.0-7625-generic-x86_64-with-Ubuntu-19.10-eoan
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
        /dev/sda
        /dev/sda1
Selected device /dev/sda
Device /dev/sda is a GPT disk...
USB disk is not mounted and can't update list widget...
Selected device /dev/sda1
Device /dev/sda1 is a GPT disk...
Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
Persistence option is available.
Persistence Max Size: 4.0G
MultiBoot Install: USB Disk: /dev/sda1
MultiBoot Install: USB Label: MULTIBOOT
MultiBoot Install: USB UUID: 32B4-7F72
MultiBoot Install: USB mount path: /media/kent/MULTIBOOT
MultiBoot Install: Disk total size: 28.8G
MultiBoot Install: Disk used size: 2.8G
MultiBoot Install: Disk free size: 26.0G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: Kingston
MultiBoot Install: Disk model: DataTraveler_3.0
MultiBoot Install: ISO file: debian-10.2.0-amd64-netinst.iso
MultiBoot Install: Distro type detected: debian-install
Persistence chosen is 0B
multibootusb directory already exists. Not copying.
EFI directory already exist. Not copying.
Installing debian-10.2.0-amd64-netinst.iso on /media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst
Executing ==> 7z -ssc-  x -y -o"/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst" "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" 2> /dev/null
ISO extracted successfully. Sync is in progress...############################|
Distro extraction completed...

Found syslinux version 6

Executing ==> /root/.multibootusb/syslinux/bin/syslinux6 -i -d "/multibootusb/debian-10.2.0-amd64-netinst/isolinux" /dev/sda1

Syslinux install on distro directory is successful...

Executing ==> dd if=/dev/sda1 of="/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst/isolinux/debian-install.bs" count=1

1+0 records in
1+0 records out
512 bytes copied, 0.111442 s, 4.6 kB/s

Bootsector copy is successful...

Using gptmbr.bin for mbr install.

Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sda1


Default syslinux install is success...


Executing ==> dd bs=440 count=1 conv=notrunc if=/usr/share/multibootusb/data/tools/gptmbr.bin of=/dev/sda
1+0 records in
1+0 records out
440 bytes copied, 0.000272612 s, 1.6 MB/s

mbr install is success...


Checking boot flag on /dev/sda

GPT Disk /dev/sda already has legacy_boot flag.

Updating distro specific config files...
In '/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst/boot/grub/grub.cfg', following paths are used as they are though they don't exist.
  /isolinux/splash.png;
  /splash.png;
Applied 2 rewrite exceptions on '/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst/install.amd/xen/debian.cfg' as shown below:
  /usr/share/doc/xen-utils-common/examples is kept as is. [1]
  /home/bozo/.Xauthority is kept as is. [1]
Updating multibootusb config file...
Using EFI/debian/grub.cfg to boot this distro.
Updating grub.cfg file...
size of the ISO is 335.0M
Updated entry in grub.cfg...
Probing 'README.mirrors.txt'!
Probing 'README.txt'!
Probing 'md5sum.txt'!
Probing 'bug-log-access.txt'!
Probing 'bug-log-mailserver.txt'!
Probing 'bug-mailserver-refcard.txt'!
Probing 'bug-maint-info.txt'!
Probing 'bug-maint-mailcontrol.txt'!
Probing 'bug-reporting.txt'!
Probing 'constitution.txt'!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 352, in install_syslinux
    config.distro, config.persistence)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 402, in update_distro_cfg_files
    callback(dirpath, f)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 374, in fix_desktop_image_in_thema_callback
    for line in f.readlines():
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 3480: invalid start byte
```

From the UI, this issue looks like #361. Other ISOs I've tested work OK

**Comment by xoxefdp** [comment]
> Also having this issue when installing debian-10.2.0
> 
> System details:
> 
> ```
> > dpkg -s python3-multibootusb | grep Version
> Version: 9.2.0-1
> > uname -a
> Linux phoenix 5.3.0-7625-generic #27~1576774560~19.10~f432cd8-Ubuntu SMP Thu Dec 19 20:35:37 UTC  x86_64 x86_64 x86_64 GNU/Linux
> > sudo fdisk -l /dev/sda
> Disk /dev/sda: 28.92 GiB, 31029460992 bytes, 60604416 sectors
> Disk model: DataTraveler 3.0
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: gpt
> Disk identifier: B7365DAC-89DB-4D0C-8994-45E0AB0B1CB4
> 
> Device      Start      End  Sectors  Size Type
> /dev/sda1  102400 60602367 60499968 28.9G Microsoft basic data
> ```
> 
> Running the operation from the UI:
> 
> ```
> > sudo multibootusb-pkexec
> Using python version  3.7.5 (default, Nov 20 2019, 09:21:52)
> [GCC 9.2.1 20191008] on platform Linux-5.3.0-7625-generic-x86_64-with-Ubuntu-19.10-eoan
> Could not find resource 'data/tools/gdisk/gdisk.exe'.
> Running multibootusb version 9.2.0 from installed system...
> Starting multibootusb GUI...
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> Cleaning old multibootusb directory...
> Syslinux exist in multibootusb directory...
> Using pyudev for detecting USB drives...
>         /dev/sda
>         /dev/sda1
> Selected device /dev/sda
> Device /dev/sda is a GPT disk...
> USB disk is not mounted and can't update list widget...
> Selected device /dev/sda1
> Device /dev/sda1 is a GPT disk...
> Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
> Persistence option is available.
> Persistence Max Size: 4.0G
> MultiBoot Install: USB Disk: /dev/sda1
> MultiBoot Install: USB Label: MULTIBOOT
> MultiBoot Install: USB UUID: 32B4-7F72
> MultiBoot Install: USB mount path: /media/kent/MULTIBOOT
> MultiBoot Install: Disk total size: 28.8G
> MultiBoot Install: Disk used size: 2.8G
> MultiBoot Install: Disk free size: 26.0G
> MultiBoot Install: Filesystem: vfat
> MultiBoot Install: Disk vendor: Kingston
> MultiBoot Install: Disk model: DataTraveler_3.0
> MultiBoot Install: ISO file: debian-10.2.0-amd64-netinst.iso
> MultiBoot Install: Distro type detected: debian-install
> Persistence chosen is 0B
> multibootusb directory already exists. Not copying.
> EFI directory already exist. Not copying.
> Installing debian-10.2.0-amd64-netinst.iso on /media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst
> Executing ==> 7z -ssc-  x -y -o"/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst" "/home/kent/Downloads/debian-10.2.0-amd64-netinst.iso" 2> /dev/null
> ISO extracted successfully. Sync is in progress...############################|
> Distro extraction completed...
> 
> Found syslinux version 6
> 
> Executing ==> /root/.multibootusb/syslinux/bin/syslinux6 -i -d "/multibootusb/debian-10.2.0-amd64-netinst/isolinux" /dev/sda1
> 
> Syslinux install on distro directory is successful...
> 
> Executing ==> dd if=/dev/sda1 of="/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst/isolinux/debian-install.bs" count=1
> 
> 1+0 records in
> 1+0 records out
> 512 bytes copied, 0.111442 s, 4.6 kB/s
> 
> Bootsector copy is successful...
> 
> Using gptmbr.bin for mbr install.
> 
> Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sda1
> 
> 
> Default syslinux install is success...
> 
> 
> Executing ==> dd bs=440 count=1 conv=notrunc if=/usr/share/multibootusb/data/tools/gptmbr.bin of=/dev/sda
> 1+0 records in
> 1+0 records out
> 440 bytes copied, 0.000272612 s, 1.6 MB/s
> 
> mbr install is success...
> 
> 
> Checking boot flag on /dev/sda
> 
> GPT Disk /dev/sda already has legacy_boot flag.
> 
> Updating distro specific config files...
> In '/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst/boot/grub/grub.cfg', following paths are used as they are though they don't exist.
>   /isolinux/splash.png;
>   /splash.png;
> Applied 2 rewrite exceptions on '/media/kent/MULTIBOOT/multibootusb/debian-10.2.0-amd64-netinst/install.amd/xen/debian.cfg' as shown below:
>   /usr/share/doc/xen-utils-common/examples is kept as is. [1]
>   /home/bozo/.Xauthority is kept as is. [1]
> Updating multibootusb config file...
> Using EFI/debian/grub.cfg to boot this distro.
> Updating grub.cfg file...
> size of the ISO is 335.0M
> Updated entry in grub.cfg...
> Probing 'README.mirrors.txt'!
> Probing 'README.txt'!
> Probing 'md5sum.txt'!
> Probing 'bug-log-access.txt'!
> Probing 'bug-log-mailserver.txt'!
> Probing 'bug-mailserver-refcard.txt'!
> Probing 'bug-maint-info.txt'!
> Probing 'bug-maint-mailcontrol.txt'!
> Probing 'bug-reporting.txt'!
> Probing 'constitution.txt'!
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 352, in install_syslinux
>     config.distro, config.persistence)
>   File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 402, in update_distro_cfg_files
>     callback(dirpath, f)
>   File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 374, in fix_desktop_image_in_thema_callback
>     for line in f.readlines():
>   File "/usr/lib/python3.7/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 3480: invalid start byte
> ```
> 
> From the UI, this issue looks like #361. Other ISOs I've tested work OK

I think this is the exact problem i got, i reference my Traceback to other posted issue #336 

Also other info about my host machine
OS: Xubuntu 18.04.5 LTS
