### ISSUE TITLE
Fail when adding hirens boot cd 15.2 iso

### ISSUE THREAD

**Issue by pkom** [mbusb/multibootusb#41]
Boot flag set to bootable on /dev/sdf
RRIP: rrip_offset 0
RRIP: rrip_offset 0
Updating main syslinux config file...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 298, in install_syslinux
    self.update_cfg_files.distro_cfg_files()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 171, in distro_cfg_files
    self.main_cfg_file()
  File "/usr/lib/python2.7/dist-packages/scripts/update_cfg.py", line 188, in main_cfg_file
    string = re.sub(r'/HBCD', '/multibootusb/' + self.iso.iso_basename() + '/HBCD', config_file)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by arunpyasi** [comment]
I got the same error !!

**Comment by mbusb** [comment]
Try the latest version 8.0.0. Fixed.
