### ISSUE TITLE
No such interface 'org.freedesktop.UDisks2.Filesystem'

### ISSUE THREAD

**Issue by mlda065** [mbusb/multibootusb#442]
# Steps to reproduce

On a fresh, headless Ubuntu 16 or 18 installation (both fail)

```
sudo apt install python3-pyqt5 p7zip-full parted util-linux python3-pyudev mtools python3-dbus python3-six
git clone git@github.com:mbusb/multibootusb.git
cd multibootusb
sudo python3 multibootusb -c -t /dev/vdc1 -i file1.iso,file2.iso
```

# Expected result

Both iso files written to `/dev/vdc1`.

# Actual Result

The script fails

```
Using python version  3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on platform Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
Running multibootusb version 9.3.0 from source...
Starting multibootusb from Command line...
25008
True
Traceback (most recent call last):
  File "/home/ubuntu/multibootusb/scripts/usb.py", line 513, in details
    details = details_udev(disk_or_partition)
  File "/home/ubuntu/multibootusb/scripts/usb.py", line 264, in details_udev
    mount_point = UDISKS.mount(usb_disk_part, remounted) or ""
  File "/home/ubuntu/multibootusb/scripts/udisks.py", line 150, in mount
    dbus_interface=self.FILESYSTEM))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.UDisks2.Filesystem' on obje
ct at path /org/freedesktop/UDisks2/block_devices/vdc1

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "multibootusb", line 227, in <module>
    main()
  File "multibootusb", line 217, in main
    cli_install_distro()
  File "/home/ubuntu/multibootusb/scripts/mbusb_cli.py", line 59, in cli_install_distro
    usb_details = details(config.usb_disk)
  File "/home/ubuntu/multibootusb/scripts/usb.py", line 515, in details
    details = details_udisks2(disk_or_partition)
  File "/home/ubuntu/multibootusb/scripts/usb.py", line 321, in details_udisks2
    mount_point = bd.Get('org.freedesktop.UDisks2.Filesystem', 'MountPoints', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.UDisks2.Filesystem'
```

I have no idea what udisks2 is. I tried `apt install udisks2`. That was installed successfully didn't fix the problem.

**Comment by moribellamy** [comment]
same issue on devuan ascii

**Comment by Hu1buerger** [comment]
My python is not great but what i had figured out after a browse through your code was that in UDISKS.mount() you are trying to create a new device in mount and udisk2 is not finding it

**Comment by soichih** [comment]
Has anyone figured out how to solve this? I am seeing the same error message.

**Comment by knoellle** [comment]
I had the same error message on arch linux, but it was fixed after I installed the package `udisks2` via pacman.

**Comment by Mielai1l** [comment]
From the required packages (as mentioned on the install page) -- python3-pyqt5 p7zip-full parted util-linux python3-pyudev mtools python3-dbus python3-six -- python3-pyudev appeared not to be installed. Installing this solved this error for me (on kubuntu 19.10)

**Comment by Mielai1l** [comment]
From the required packages (as mentioned on the install page) -- python3-pyqt5 p7zip-full parted util-linux python3-pyudev mtools python3-dbus python3-six -- python3-pyudev appeared not to be installed. Installing this solved this error for me (on kubuntu 19.10)

**Comment by dcrobertson01** [comment]
I installed a pre built package - those requirements are on the '--from source code' section.

Also - python3-pyudev is already installed. All the requirements are installed.

**Comment by jake-87** [comment]
Hi, sorry to reopen a dead error, but i am also experiencing this error. I already have python3-pyudev installed. I am on void linux, anyone got any ideas? i can provide crash logs on request.

**Comment by jake-87** [comment]
Fixed. Had to both rm -rf the USB and  reinstall multibootusb.
