### ISSUE TITLE
Unable to boot USB/ISO after QEMU update

### ISSUE THREAD

**Issue by emailradhesh** [mbusb/multibootusb#444]
### What was the activity?

1. Install qemu on host OS.
`Start-Date: 2019-03-04  14:04:14
Commandline: apt-get -y install qemu
Requested-By: user (1000)
Install: libusbredirparser1:amd64 (0.7.1-1, automatic), seabios:amd64 (1.10.2-1ubuntu1, automatic), ipxe-qemu:amd64 (1.0.0+git-20180124.fbe8c52d-0ubuntu2.1, automatic), qemu-system-mips:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), libibverbs1:amd64 (17.1-1ubuntu0.1, automatic), qemu-system-misc:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), qemu-system-ppc:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), msr-tools:amd64 (1.3-2build1, automatic), librbd1:amd64 (12.2.8-0ubuntu0.18.04.2, automatic), ibverbs-providers:amd64 (17.1-1ubuntu0.1, automatic), qemu-system-x86:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), libbrlapi0.6:amd64 (5.5-4ubuntu2.0.1, automatic), qemu-system-s390x:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), librdmacm1:amd64 (17.1-1ubuntu0.1, automatic), qemu-user:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), libspice-server1:amd64 (0.14.0-1ubuntu2.4, automatic), qemu:amd64 (1:2.11+dfsg-1ubuntu7.9), libxenstore3.0:amd64 (4.9.2-0ubuntu1, automatic), qemu-utils:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), libcacard0:amd64 (1:2.5.0-3, automatic), qemu-system-sparc:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), sharutils:amd64 (1:4.15.2-3, automatic), ipxe-qemu-256k-compat-efi-roms:amd64 (1.0.0+git-20150424.a25a16d-0ubuntu2, automatic), qemu-user-binfmt:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), libxen-4.9:amd64 (4.9.2-0ubuntu1, automatic), binfmt-support:amd64 (2.1.8-2, automatic), libfdt1:amd64 (1.4.5-3, automatic), libiscsi7:amd64 (1.17.0-1.1, automatic), qemu-slof:amd64 (20170724+dfsg-1ubuntu1, automatic), cpu-checker:amd64 (0.7-0ubuntu7, automatic), qemu-system-arm:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), qemu-block-extra:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), librados2:amd64 (12.2.8-0ubuntu0.18.04.2, automatic), qemu-system-common:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic), qemu-system:amd64 (1:2.11+dfsg-1ubuntu7.9, automatic)
End-Date: 2019-03-04  14:04:53`
2. Run sudo python3 /projects/multibootusb/multibootusb
3. Was able to boot from ISO or USB.
4. Upgrade qemu on host OS.
`Start-Date: 2019-03-05  08:31:30
Commandline: apt-get -y upgrade
Requested-By: user (1000)
Upgrade: ipxe-qemu:amd64 (1.0.0+git-20180124.fbe8c52d-0ubuntu2.1, 1.0.0+git-20180124.fbe8c52d-0ubuntu2.2), qemu-system-mips:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-system-misc:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-system-ppc:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-system-x86:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-system-s390x:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-user:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), initramfs-tools-bin:amd64 (0.130ubuntu3.6, 0.130ubuntu3.7), qemu:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-utils:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-system-sparc:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-user-binfmt:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), openssh-client:amd64 (1:7.6p1-4ubuntu0.2, 1:7.6p1-4ubuntu0.3), qemu-system-arm:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-block-extra:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), qemu-system-common:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10), initramfs-tools-core:amd64 (0.130ubuntu3.6, 0.130ubuntu3.7), initramfs-tools:amd64 (0.130ubuntu3.6, 0.130ubuntu3.7), qemu-system:amd64 (1:2.11+dfsg-1ubuntu7.9, 1:2.11+dfsg-1ubuntu7.10)
End-Date: 2019-03-05  08:32:41`
2. Run sudo python3 /projects/multibootusb/multibootusb
3. Wasn't able to boot from ISO or USB.
4. Error displayed was
`Using python version  3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on platform Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
Running multibootusb version 9.3.0 from source...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
/sbin/fsck.vfat
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
        /dev/sdb
        /dev/sdb1
        /dev/sdb2
Device /dev/sdb is an MBR disk.
Selected device /dev/sdb
USB disk is not mounted and can't update list widget...
QEMU: USB RAM = 2048
/usr/bin/qemu-system-x86_64
QEMU: using qemu-system-x86_64
Executing ==> ['qemu-system-x86_64', '-m', '2048', '-enable-kvm', '-hda', '/dev/sdb', '-vga', 'std']
ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
qemu-system-x86_64: failed to initialize KVM: Device or resource busy
Traceback (most recent call last):
  File "projects/multibootusb/scripts/qemu.py", line 64, in run_qemu
    out = subprocess.check_output(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['qemu-system-x86_64', '-m', '2048', '-enable-kvm', '-hda', '/dev/sdb', '-vga', 'std']' returned non-zero exit status 1.
`

**Comment by emailradhesh** [comment]
This issue shall be closed now as Ubuntu delivered Linux kernel (headers, images) which is compatible with QEMU update. 

The error is no more coming in multibootusb
