### ISSUE TITLE
Interface freezes when it installes syslinux

### ISSUE THREAD

**Issue by jorisrietveld** [mbusb/multibootusb#447]
#  Installation fails on syslinux
Hi, I was trying to install Ubuntu 18.04 on a USB disk that I have used before (and created) with multibootusb. When I launch it from the application menu it extract the ISO and then it says installing syslinux but this never progresses anything (was doing something else and checked about an hour later). So I closed it and tried to run it from the terminal as root so I could see what was going on. It launged the GUI but it did not show ubuntu in the installed distro list. I checked and found that they were present in the multibootusb/ directory. I removed the Ubuntu folder and checked the `syslinux.cfg` and`exlinux.cfg` and `grub/grub.cfg` files and remove the ubuntu part in `exlinux.cfg`.

Then I selected the ISO and attempted to add it and got this output:
```console
Using python version  3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on platform Linux-4.15.0-47-generic-x86_64-with-neon-18.04-bionic
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
	/dev/sdb
	/dev/sdb1
Selected device /dev/sdb
Device /dev/sdb is a GPT disk...
USB disk is not mounted and can't update list widget...
Selected device /dev/sdb1
Device /dev/sdb1 is a GPT disk...
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
Persistence option is available.
Persistence Max Size: 1.1G
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 987, resource id: 27263308, major code: 40 (TranslateCoords), minor code: 0
MultiBoot Install: USB Disk: /dev/sdb1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 13.4G
MultiBoot Install: Disk free size: 1.1G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1229, resource id: 27263322, major code: 40 (TranslateCoords), minor code: 0
MultiBoot Install: USB Disk: /dev/sdb1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 13.4G
MultiBoot Install: Disk free size: 1.1G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1890, resource id: 27263343, major code: 40 (TranslateCoords), minor code: 0
MultiBoot Install: USB Disk: /dev/sdb1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 11.6G
MultiBoot Install: Disk free size: 2.9G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2400, resource id: 27263372, major code: 40 (TranslateCoords), minor code: 0
No USB disk found...
Using pyudev for detecting USB drives...
	/dev/sdb
	/dev/sdb1
Selected device /dev/sdb
Device /dev/sdb is a GPT disk...
USB disk is not mounted and can't update list widget...
Selected device /dev/sdb1
Device /dev/sdb1 is a GPT disk...
MultiBoot Install: USB Disk: /dev/sdb1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 11.6G
MultiBoot Install: Disk free size: 2.9G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2761, resource id: 27263381, major code: 40 (TranslateCoords), minor code: 0
No USB disk found...
Using pyudev for detecting USB drives...
	/dev/sdc
	/dev/sdc1
Selected device /dev/sdc
Device /dev/sdc is a GPT disk...
USB disk is not mounted and can't update list widget...
Selected device /dev/sdc1
Device /dev/sdc1 is a GPT disk...
MultiBoot Install: USB Disk: /dev/sdc1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 11.6G
MultiBoot Install: Disk free size: 2.9G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
Persistence chosen is 0B
multibootusb directory already exists. Not copying.
EFI directory already exist. Not copying.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3376, resource id: 27263487, major code: 40 (TranslateCoords), minor code: 0
  0% |                                                              86% |#############################################################Installing ubuntu-18.04.2-desktop-amd64.iso on /media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64
Executing ==> 7z -ssc-  x -y -o"/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64" "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" 2> /dev/null
 87% |############################################################# 88% |############################################################# 89% |############################################################# 90% |############################################################# 91% |############################################################# 92% |############################################################# 93% |############################################################# 94% |############################################################# 95% |############################################################# 96% |############################################################# 97% |############################################################# 98% |############################################################# 99% |#############################################################100% |#############################################################ISO extracted successfully. Sync is in progress...
Distro extraction completed...

Found syslinux version 6

Executing ==> /root/.multibootusb/syslinux/bin/syslinux6 -i -d "/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux" /dev/sdc1

Syslinux install on distro directory is successful...

Executing ==> dd if=/dev/sdc1 of="/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux/ubuntu.bs" count=1

1+0 records in
1+0 records out
512 bytes copied, 0,000191996 s, 2,7 MB/s

Bootsector copy is successful...

Using gptmbr.bin for mbr install.
Could not find resource 'data/tools/gptmbr.bin'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 349, in install_syslinux
    syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 107, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: must be str, not NoneType
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_multibootusb.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 349, in install_syslinux
    syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 107, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: must be str, not NoneType
```
It froze again so I tried run it as my normal user (with sudo) from the terminal like:
```console
sudo multibootusb 
# And like this:
sudo multibootusb -d
```
I get this output: 
```console         
[sudo] password for neon2019: 
sh: 0: getcwd() failed: No such file or directory
Using python version  3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on platform Linux-4.15.0-47-generic-x86_64-with-neon-18.04-bionic
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```
At last I tried to run it as root like:
```console
sudo multibootusb -d
```
And got this output:
```console
Using python version  3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on platform Linux-4.15.0-47-generic-x86_64-with-neon-18.04-bionic
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 6, in <module>
    from colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 188, in <module>
    from scripts.debug import colors
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 11, in <module>
    raise e
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 9, in <module>
    from .colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'scripts.colorama'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_multibootusb.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 6, in <module>
    from colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 188, in <module>
    from scripts.debug import colors
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 11, in <module>
    raise e
  File "/usr/lib/python3/dist-packages/scripts/debug.py", line 9, in <module>
    from .colorama import init as colorama_init, Fore, Back, Style
ModuleNotFoundError: No module named 'scripts.colorama'
```
The errors seem to be unrelated to me but I have almost no experience with python, I actually stated to learn it for OpenCV at school about a week a go. I got the `ModuleNotFoundError: No module named 'colorama'` message fixed by installing `colorama` with pip. But unfortunatly it froze again and showed:
```console
Using python version  3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on platform Linux-4.15.0-47-generic-x86_64-with-neon-18.04-bionic
Could not find resource 'data/tools/gdisk/gdisk.exe'.
=== DEBUG ENABLED ===
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
	/dev/sdb
	/dev/sdb1
Selected device /dev/sdb
Device /dev/sdb is a GPT disk...
USB disk is not mounted and can't update list widget...
Selected device /dev/sdb1
Device /dev/sdb1 is a GPT disk...
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
Persistence option is available.
Persistence Max Size: 1.1G
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1011, resource id: 27263741, major code: 40 (TranslateCoords), minor code: 0
MultiBoot Install: USB Disk: /dev/sdb1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 13.4G
MultiBoot Install: Disk free size: 1.1G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1183, resource id: 27263749, major code: 40 (TranslateCoords), minor code: 0
MultiBoot Install: USB Disk: /dev/sdb1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 11.6G
MultiBoot Install: Disk free size: 2.9G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
Persistence chosen is 0B
multibootusb directory already exists. Not copying.
EFI directory already exist. Not copying.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1516, resource id: 27263770, major code: 40 (TranslateCoords), minor code: 0
  0% |                                                                     86% |#############################################################       Installing ubuntu-18.04.2-desktop-amd64.iso on /media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64
Executing ==> 7z -ssc-  x -y -o"/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64" "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" 2> /dev/null
 87% |##############################################################       88% |###############################################################      89% |################################################################     90% |################################################################     91% |#################################################################    92% |##################################################################   93% |##################################################################   94% |###################################################################  95% |#################################################################### 96% |#################################################################### 97% |#################################################################### 98% |#################################################################### 99% |####################################################################100% |####################################################################ISO extracted successfully. Sync is in progress...
Distro extraction completed...

Found syslinux version 6

Executing ==> /root/.multibootusb/syslinux/bin/syslinux6 -i -d "/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux" /dev/sdb1

Syslinux install on distro directory is successful...

Executing ==> dd if=/dev/sdb1 of="/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux/ubuntu.bs" count=1

1+0 records in
1+0 records out
512 bytes copied, 0,0019903 s, 257 kB/s

Bootsector copy is successful...

Using gptmbr.bin for mbr install.
Could not find resource 'data/tools/gptmbr.bin'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 349, in install_syslinux
    syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 107, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: must be str, not NoneType
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_multibootusb.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 349, in install_syslinux
    syslinux_default(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 107, in syslinux_default
    mbr_install_cmd = 'dd bs=440 count=1 conv=notrunc if=' + mbr_bin + ' of=' + usb_disk[:-1]
TypeError: must be str, not NoneType

```
Is there anything I could do to solve this issue or provide debug information, just ask

Kind Regards,
Joris Rietveld

**Comment by shinji-s** [comment]
See https://github.com/mbusb/multibootusb/issues/361
My hunch says you may have other problems, though.

**Comment by jorisrietveld** [comment]
Thanks for your fast reply, I solved it with
```console
wget https://raw.githubusercontent.com/mbusb/multibootusb/master/data/tools/gptmbr.bin -O /usr/share/multibootusb/data/tools
```
It worked I will try booting it later. Would it mean that the inconsistent errors that showed up while trying to install it. is because I screwed something up on my system that I should fix? 
This was the output for completeness:
```console
Using python version  3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on platform Linux-4.15.0-47-generic-x86_64-with-neon-18.04-bionic
Could not find resource 'data/tools/gdisk/gdisk.exe'.
=== DEBUG ENABLED ===
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
	/dev/sdc
	/dev/sdc1
Selected device /dev/sdc
Device /dev/sdc is a GPT disk...
USB disk is not mounted and can't update list widget...
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
Persistence option is available.
Persistence Max Size: Unknown
Selected device /dev/sdc1
Device /dev/sdc1 is a GPT disk...
MultiBoot Install: USB Disk: /dev/sdc1
MultiBoot Install: USB Label: 
MultiBoot Install: USB UUID: 7618-046B
MultiBoot Install: USB mount path: /media/neon2019/7618-046B
MultiBoot Install: Disk total size: 14.5G
MultiBoot Install: Disk used size: 11.6G
MultiBoot Install: Disk free size: 2.9G
MultiBoot Install: Filesystem: vfat
MultiBoot Install: Disk vendor: SanDisk
MultiBoot Install: Disk model: Cruzer_Blade
MultiBoot Install: ISO file: ubuntu-18.04.2-desktop-amd64.iso
MultiBoot Install: Distro type detected: ubuntu
Persistence chosen is 0B
multibootusb directory already exists. Not copying.
EFI directory already exist. Not copying.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1145, resource id: 27263873, major code: 40 (TranslateCoords), minor code: 0
  0% |                                                                     86% |#############################################################       Installing ubuntu-18.04.2-desktop-amd64.iso on /media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64
Executing ==> 7z -ssc-  x -y -o"/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64" "/home/shared/OS_Collection/ubuntu-18.04.2-desktop-amd64.iso" 2> /dev/null
 87% |##############################################################       88% |###############################################################      89% |################################################################     90% |################################################################     91% |#################################################################    92% |##################################################################   93% |##################################################################   94% |###################################################################  95% |#################################################################### 96% |#################################################################### 97% |#################################################################### 98% |#################################################################### 99% |####################################################################100% |####################################################################ISO extracted successfully. Sync is in progress...
Distro extraction completed...

Found syslinux version 6

Executing ==> /root/.multibootusb/syslinux/bin/syslinux6 -i -d "/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux" /dev/sdc1

Syslinux install on distro directory is successful...

Executing ==> dd if=/dev/sdc1 of="/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux/ubuntu.bs" count=1

1+0 records in
1+0 records out
512 bytes copied, 0,000255866 s, 2,0 MB/s

Bootsector copy is successful...

Using gptmbr.bin for mbr install.

Executing ==> /root/.multibootusb/syslinux/bin/syslinux4 -i -d multibootusb /dev/sdc1


Default syslinux install is success...


Executing ==> dd bs=440 count=1 conv=notrunc if=/usr/share/multibootusb/data/tools/gptmbr.bin of=/dev/sdc
1+0 records in
1+0 records out
440 bytes copied, 0,000108118 s, 4,1 MB/s

mbr install is success...


Checking boot flag on /dev/sdc

GPT Disk /dev/sdc already has legacy_boot flag.

Updating distro specific config files...
Applied 3 rewrite exceptions on '/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64/boot/grub/grub.cfg' as shown below:
  /cdrom/preseed/ubuntu.seed is kept as is. [3]
Applied 2 rewrite exceptions on '/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64/boot/grub/loopback.cfg' as shown below:
  /cdrom/preseed/ubuntu.seed is kept as is. [2]
In '/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux/rqtxt.cfg', following paths are used as they are though they don't exist.
  /install/vmlinuz
  /install/initrd.gz
Applied 2 rewrite exceptions on '/media/neon2019/7618-046B/multibootusb/ubuntu-18.04.2-desktop-amd64/isolinux/txt.cfg' as shown below:
  /cdrom/preseed/ubuntu.seed is kept as is. [2]
Updating multibootusb config file...
Using boot/grub/loopback.cfg to boot this distro.
Updating grub.cfg file...
size of the ISO is 1.9G
Updated entry in grub.cfg...
Probing 'md5sum.txt'!
Probing 'f1.txt'!
Probing 'f10.txt'!
Probing 'f2.txt'!
Probing 'f3.txt'!
Probing 'f4.txt'!
Probing 'f5.txt'!
Probing 'f6.txt'!
Probing 'f7.txt'!
Probing 'f8.txt'!
Probing 'f9.txt'!
Updated entry in syslinux.cfg...
multibootusb EFI image already exist. Not copying...
ubuntu-18.04.2-desktop-amd64.iso has been successfully installed.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1361, resource id: 27263882, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by shinji-s** [comment]
No. It is not your fault. The package you installed is incomplete.
If you are in learning mode I would recommend trying devel branch in the github repository.

**Comment by jorisrietveld** [comment]
Thanks again for your reaction, I am going to play around with it and mark this issue as closed.
