### ISSUE TITLE
multibootusb broken on ubuntu 18.04

### ISSUE THREAD

**Issue by dabrain34** [mbusb/multibootusb#479]
I'm unable to install an ISO such as doudoulinux, 
it stucks on installing syslinux for ever after copying the iso correctly.
Any idea to workaround this ?

**Comment by dabrain34** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 352, in install_syslinux
    config.distro, config.persistence)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 402, in update_distro_cfg_files
    callback(dirpath, f)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 374, in fix_desktop_image_in_thema_callback
    for line in f.readlines():
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 2126: invalid start byte

**Comment by dabrain34** [comment]
happens the same with a debian ISO debian-testing-amd64-xfce-CD-1.iso

**Comment by dabrain34** [comment]
related #403
