### ISSUE TITLE
can't launch with sudo even in command line mode on wayland

### ISSUE THREAD

**Issue by Soundtoxin** [mbusb/multibootusb#487]
Launching graphical stuff on wayland with root privileges is purposefully broken for security reasons. There are apparently some workarounds with `xhost` to temporarily let you launch graphical stuff with root privileges, but they aren't working for me.
What's weird is I seem to get the same error even using the -c option. I'm on NixOS using Sway. Using the version of multibootusb that was in the distro repos.

graphical attempt
```
brad@anpan:~/ > sudo multibootusb                                                                                                                              
Using python version  3.6.9 (default, Jul  2 2019, 20:43:20)                                                                                                   
[GCC 8.3.0] on platform Linux-4.19.84-x86_64-with-glibc2.3.4                                                                                                   
Traceback (most recent call last):                                                                                                                             
  File "/nix/store/jkxgn5l9kdnfjbm48srrymmv68gjaziw-multibootusb-9.2.0/bin/.multibootusb-wrapped", line 216, in <module>                                       
    running_from()                                                                                                                                             
  File "/nix/store/jkxgn5l9kdnfjbm48srrymmv68gjaziw-multibootusb-9.2.0/bin/.multibootusb-wrapped", line 54, in running_from                                    
    gen.log('Using python version ' + python_version + 'on platform ' + _platform, _print=False)                                                               
  File "/nix/store/jkxgn5l9kdnfjbm48srrymmv68gjaziw-multibootusb-9.2.0/lib/python3.6/site-packages/scripts/gen.py", line 45, in log                            
    level=logging.DEBUG)                                                                                                                                       
  File "/nix/store/fbnrrriw5zyn1mlxsd49xrs5rn2mv7pm-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1808, in basicConfig                                
    h = FileHandler(filename, mode)                                                                                                                            
  File "/nix/store/fbnrrriw5zyn1mlxsd49xrs5rn2mv7pm-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1032, in __init__                                   
    StreamHandler.__init__(self, self._open())                                                                                                                 
  File "/nix/store/fbnrrriw5zyn1mlxsd49xrs5rn2mv7pm-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1061, in _open                                      
    return open(self.baseFilename, self.mode, encoding=self.encoding)                                                                                          
PermissionError: [Errno 13] Permission denied: '/tmp/multibootusb.log'                                                                                         

```
command line mode attempt
```
brad@anpan:~/ > sudo multibootusb -c -i Downloads/nixos-graphical-19.09.1320.4ad6f1404a8-x86_64-linux.iso,Downloads/guix-system-install-1.0.1.x86_64-linux.iso,Downloads/helium-5-amd64.hybrid.iso -t /dev/sdc1
Using python version  3.6.9 (default, Jul  2 2019, 20:43:20) 
[GCC 8.3.0] on platform Linux-4.19.84-x86_64-with-glibc2.3.4
Traceback (most recent call last):
  File "/nix/store/jkxgn5l9kdnfjbm48srrymmv68gjaziw-multibootusb-9.2.0/bin/.multibootusb-wrapped", line 212, in <module>
    running_from()
  File "/nix/store/jkxgn5l9kdnfjbm48srrymmv68gjaziw-multibootusb-9.2.0/bin/.multibootusb-wrapped", line 54, in running_from
    gen.log('Using python version ' + python_version + 'on platform ' + _platform, _print=False)
  File "/nix/store/jkxgn5l9kdnfjbm48srrymmv68gjaziw-multibootusb-9.2.0/lib/python3.6/site-packages/scripts/gen.py", line 45, in log
    level=logging.DEBUG)
  File "/nix/store/fbnrrriw5zyn1mlxsd49xrs5rn2mv7pm-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/nix/store/fbnrrriw5zyn1mlxsd49xrs5rn2mv7pm-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/nix/store/fbnrrriw5zyn1mlxsd49xrs5rn2mv7pm-python3-3.6.9/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/multibootusb.log'

```

**Comment by andersk** [comment]
@Soundtoxin It should work if you `rm /tmp/multibootusb.log` first.

That said, using a fixed or predictable filename in `/tmp`, in addition to causing this practical problem, may be a security vulnerability. MultiBootUSB should use a secure API like `tempfile.NamedTemporaryFile` for this.

**Comment by Soundtoxin** [comment]
> It should work if you `rm /tmp/multibootusb.log` first.

Thank you! It's actually doing something instead of failing instantly now.
