### ISSUE TITLE
Error after Unmounting (Disk not synced after Bootsector copy?)

### ISSUE THREAD

**Issue by bartman081523** [mbusb/multibootusb#492]
> sudo ./multibootusb -c -i /home/username/Downloads/ubuntu-mini-amd64.iso -t /dev/sdd1
> Using python version  3.7.4 (default, Oct  4 2019, 06:57:26) 
> [GCC 9.2.0] on platform Linux-5.3.12-1-MANJARO-x86_64-with-arch-Manjaro-Linux
> Running multibootusb version 9.3.0 from source...
> Starting multibootusb from Command line...
> 25008
> True
> Device /dev/sdd1 is an MBR disk.
> Cleaning old multibootusb directory...
> Syslinux exist in multibootusb directory...
> Executing ==> 7z -ssc-  x -y "/home/username/Downloads/mini.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/username/Downloads/mini.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/username/Downloads/mini.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
> Executing ==> 7z -ssc-  x -y "/home/username/Downloads/mini.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
> Initiating installation process for mini
> Detected distro type is    :memdisk_iso
> 
> Selected ISO is          :"mini.iso"
> Selected target device is  :"/dev/sdd1"
> Please confirm the option.
> Y/y/Yes/yes/YES or N/n/No/no/NO
> Please enter the option listed above : Y
> Copying multibootusb directory to /run/media/username/A810-1B22
> EFI/BOOT directory does not exist. Creating new.
> Copying EFI directory to /run/media/username/A810-1B22
> Installing mini.iso on /run/media/username/A810-1B22/multibootusb/mini                                                                                                                                              |
> 100% |############################################################################################################################################################################################################|
> Found syslinux version 6
> 
> 
> Found syslinux version 6
> 
> Unmounting /dev/sdd1
> Unmounted /dev/sdd1
> Executing ==> ['/root/.multibootusb/syslinux/bin/syslinux6', '-f', '-i', '-d', '/multibootusb/mini/', '/dev/sdd1']
> 
> Syslinux install on distro directory is successful...
> 
> Executing ==> ['dd', 'if=/dev/sdd1', 'of=/tmp/mbusb_temp.bs', 'count=1']
> 
> 1+0 Datensätze ein
> 1+0 Datensätze aus
> 512 bytes copied, 0,00499326 s, 103 kB/s
> 
> Bootsector copy is successful...
> 
> Mounted /dev/sdd1
> Unmouting /dev/sdd1 at exit
> Traceback (most recent call last):
>   File "./multibootusb", line 227, in <module>
>     main()
>   File "./multibootusb", line 217, in main
>     cli_install_distro()
>   File "/home/username/Desktop/build/multibootusb/scripts/mbusb_cli.py", line 75, in cli_install_distro
>     iso_install(config.image_path)
>   File "/home/username/Desktop/build/multibootusb/scripts/mbusb_cli.py", line 112, in iso_install
>     syslinux_distro_dir(config.usb_disk, iso_image, _distro)
>   File "/home/username/Desktop/build/multibootusb/scripts/syslinux.py", line 332, in syslinux_distro_dir
>     distro_sys_install_bs)
>   File "/home/username/Desktop/build/multibootusb/scripts/syslinux.py", line 236, in build_distro_bootsector
>     shutil.copy(tmp_bs, distro_sys_install_bs)
>   File "/usr/lib/python3.7/shutil.py", line 248, in copy
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: '/run/media/username/A810-1B22/multibootusb/mini/memdisk_iso.bs'

**Comment by bartman081523** [comment]
@mbusb i will test but think it can be closed
edit: can be closed, boot sector copy successful

testing with ubuntu-mini-amd64.iso
result: 
Bios Boot (Syslnux) : succeeds from menuentry ubuntu-mini-amd64
UEFI Boot (Grub) : menuentry "search for isos and boot" succeeds when ISO file resides in [usbdrive]/multibootusb/iso/
