### ISSUE TITLE
Cannot run application due to undefined name.

### ISSUE THREAD

**Issue by lzlrd** [mbusb/multibootusb#494]
I installed https://github.com/mbusb/multibootusb/releases/download/v9.2.0/python3-multibootusb_9.2.0-1_all.deb and have the following results upon trying to run the program:
```
$ multibootusb-pkexec
Using python version  3.7.5 (default, Oct 27 2019, 15:43:29) 
[GCC 9.2.1 20191022] on platform Linux-5.4.2-xanmod2-x86_64-with-debian-bullseye-sid
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```

I decided then to try using the CLI tool but that failed too, as shown below.
```
$ sudo multibootusb -c -y -i Downloads/pmagic_2018_01_08.iso,Downloads/debian-live-testing-amd64-kde+nonfree.iso -t /dev/sdf
Using python version  3.7.5 (default, Oct 27 2019, 15:43:29) 
[GCC 9.2.1 20191022] on platform Linux-5.4.2-xanmod2-x86_64-with-debian-bullseye-sid
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 172, in <module>
    config.yes = True
NameError: name 'config' is not defined
```

The error appears on both X11 and Wayland.

**Comment by lzlrd** [comment]
I understand there seem to be similar issues but I could not find a fix using any of the sugggestions provided. In the situation I have it's extremely unpreferred to run the application from source however I tried it and it also failed (both devel and master) seemingly due to it not supporting Wayland.

**Comment by shinji-s** [comment]
AFIK if you do 'sudo multiboootusb ...' the script 'multibootusb' will be sought in PATH and what's found may not be what you want to run.
If you did the same while experimenting with sources from github, try 'sudo python multibootusb ...'  in the root of source tree. I believe at least devel branch should give you better info than "'config' is not defined".

**Comment by sushidub** [comment]
Same issue here building from source
**GCC 4.7.3 - on platform Linux-3.16.5-gentoo-x86_64-Intel-R-_Core-TM-_i5-2410M_CPU_@_2.30GHz-with-gentoo-2.2**

```sh
Traceback (most recent call last):
  File "./multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined
```
Did my best to circumvent but gave up. Would love to use this tho.

**Comment by lpapadakos** [comment]
As it is, it cant import the scripts from the scripts directory if it's installed globally (I'm sure there's a solution for this)
For now, don't use the aur package. Do a git clone in your user folder and run the script in its working directory.
