### ISSUE TITLE
Release 9.2.0 fails to launch permission error while opening /tmp/multibootusb.log

### ISSUE THREAD

**Issue by AkechiShiro** [mbusb/multibootusb#526]
I've just downloaded the package that is of version 9.2.0 and extracted it from the tar archive, I'm running this on PopOS 20.04 (kernel 5.4.0).
I've then run the following command and got an error about a permission which I found pretty weird since the program is executed with `sudo` and thus has root privileges hence this error should be related to something else I guess.

```py 
sudo python3 ./multibootusb
./multibootusb:194: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if uninstall is True and config.usb_disk is not '':
./multibootusb:196: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif uninstall is True and config.usb_disk is '':
./multibootusb:200: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' and config.usb_disk is '':
./multibootusb:200: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' and config.usb_disk is '':
./multibootusb:203: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif config.cli_syslinux is True and config.usb_disk is not '':
./multibootusb:205: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' or config.usb_disk is '':
./multibootusb:205: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' or config.usb_disk is '':
Using python version  3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on platform Linux-5.4.0-7642-generic-x86_64-with-glibc2.29
Traceback (most recent call last):
  File "./multibootusb", line 215, in <module>
    running_from()
  File "./multibootusb", line 53, in running_from
    gen.log('Using python version ' + python_version + 'on platform ' + _platform, _print=False)
  File "/home/akechi/downloads/utilitybin/multibootusb-9.2.0/scripts/gen.py", line 41, in log
    logging.basicConfig(filename=LOG_FILE_PATH,
  File "/usr/lib/python3.8/logging/__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/multibootusb.log'
```

Here is what that file contains :
```bash
19:17:40.549 root INFO Using python version 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]on platform Linux-5.4.0-7642-generic-x86_64-with-glibc2.29
19:17:40.550 root INFO Running multibootusb version 9.2.0 from source...
19:17:40.559 root INFO Starting multibootusb GUI...
19:17:40.560 root DEBUG 

Admin privilege is required to run multibootusb.
 If you are running from source try 'sudo python3 ./multibootusb'
 or you can try 'multibootusb-pkexec' (post install)


19:22:05.896 root INFO Could not find resource 'data/tools/gdisk/gdisk.exe'.
19:22:05.929 root INFO Using python version 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]on platform Linux-5.4.0-7642-generic-x86_64-with-glibc2.29
19:22:05.929 root INFO Running multibootusb version 9.2.0 from installed system...
19:22:05.931 root INFO Starting multibootusb GUI...
19:22:05.931 root DEBUG 

Admin privilege is required to run multibootusb.
 If you are running from source try 'sudo python3 ./multibootusb'
 or you can try 'multibootusb-pkexec' (post install)
```
Running `multibootusb-pkexec` shows no output but ends successfully with a 0 exit code.

**Comment by AkechiShiro** [comment]
Closing this issue as it looks like this project is not being maintained anymore. I suggest to anyone to use this [instead for making multiboot USB.](https://github.com/ventoy/Ventoy)
