### ISSUE TITLE
Debian-like : problem to write on USBKey

### ISSUE THREAD

**Issue by will-tam** [mbusb/multibootusb#529]
Hello.

First, i found it's very nice you did. We always many thinks with Window$, but yours also run with Linux.
Great.

But... T_T

When i want install Debian-like distros (Debian it-self, or Rapsbian), it always "congrate" me with this exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 352, in install_syslinux
    config.distro, config.persistence)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 402, in update_distro_cfg_files
    callback(dirpath, f)
  File "/usr/lib/python3/dist-packages/scripts/update_cfg_file.py", line 374, in fix_desktop_image_in_thema_callback
    for line in f.readlines():
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 3480: invalid start byte

This, always after this:
Probing 'constitution.txt'!

Of course, when i choose this ISO to run, it fail.

Best regards.

**Comment by daks** [comment]
I got the exact same problem trying to add a Debian 10 boot option using the released version 9.2.0-1
