### ISSUE TITLE
on Fedora....

### ISSUE THREAD

**Issue by dabzse** [mbusb/multibootusb#550]
[root@host user]# multibootusb
/usr/local/bin/multibootusb:194: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if uninstall is True and config.usb_disk is not '':
/usr/local/bin/multibootusb:196: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif uninstall is True and config.usb_disk is '':
/usr/local/bin/multibootusb:200: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' and config.usb_disk is '':
/usr/local/bin/multibootusb:200: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' and config.usb_disk is '':
/usr/local/bin/multibootusb:203: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif config.cli_syslinux is True and config.usb_disk is not '':
/usr/local/bin/multibootusb:205: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' or config.usb_disk is '':
/usr/local/bin/multibootusb:205: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif config.image_path is '' or config.usb_disk is '':
Using python version  3.9.6 (default, Jul 16 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)] on platform Linux-5.13.5-100.fc33.x86_64-x86_64-with-glibc2.32
Could not find resource 'data/tools/gdisk/gdisk.exe'.
Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined

**Comment by smilingblackcat** [comment]
Those were simple: I got thru those by editing the script to use "==" and "!="  since those statements are comparing to VALUES, not identity.

Now I'm getting 

  File "/usr/local/bin/multibootusb", line 187, in <module>
    if config.debug is True:
NameError: name 'config' is not defined

Back to digging
