### ISSUE TITLE
Crash after second drop-down-list

### ISSUE THREAD

**Issue by arnonuehm66** [mbusb/multibootusb#565]
The program crashes every time after the second value from  the two drop-down-lists "Select USB disk" and "Select image" was selected .

On a Manjaro box last updated 2022-06-29.

**Comment by Gaspartame** [comment]
Same on manjaro, this is my log if it helps : 


```
Using python version  3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801] on platform Linux-6.5.9-1-MANJARO-x86_64-with-glibc2.38
Could not find resource 'data/tools/gdisk/gdisk.exe
Running multibootusb version 9.2.0 from installed system...
Starting multibootusb GUI...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Cleaning old multibootusb directory...
Syslinux exist in multibootusb directory...
Using pyudev for detecting USB drives...
        /dev/sda
        /dev/sda1
Selected device /dev/sda
Device /dev/sda is a MBR disk...
USB disk is not mounted and can't update list widget...
Selected device /dev/sda1
Device /dev/sda1 is a MBR disk...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Executing ==> 7z -ssc-  x -y "/home/user/Downloads/sparkylinux-7.1-i686-minimalgui.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.cfg" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/user/Downloads/sparkylinux-7.1-i686-minimalgui.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.txt" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/user/Downloads/sparkylinux-7.1-i686-minimalgui.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*isolinux.bin" -r 2> /dev/null
Executing ==> 7z -ssc-  x -y "/home/user/Downloads/sparkylinux-7.1-i686-minimalgui.iso" -o"/root/.multibootusb/iso_cfg_ext_dir" "*.lst" -r 2> /dev/null
Persistence option is available.
Persistence Max Size: 4.0G
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/scripts/mbusb_gui.py", line 286, in browse_iso
    self.ui_update_persistence()
  File "/usr/lib/python3.11/site-packages/scripts/mbusb_gui.py", line 303, in ui_update_persistence
    self.ui.slider_persistence.setMaximum(config.persistence_max_size / 1024 / 1024)
TypeError: setMaximum(self, a0: int): argument 1 has unexpected type 'float'
zsh: IOT instruction  sudo multibootusb
```
note : I don't know why, I successfully flashed other images, but this sparkylinux image won't flash (md5 : 0eaf8d5da1b497551b2ba44f35c51117)

**Comment by doc75** [comment]
i got the same issue on debian 13, and using the command line worked fine (with less control over the options)
