### ISSUE TITLE
Not able to start it

### ISSUE THREAD

**Issue by Tr4sK** [mbusb/multibootusb#62]
HI,
I’m on debian testing and I’m not able to use it once installed :(

Here is the output log. Good luck :)

```bash
┌─[tr4sk@beigebox] - [~/script/multibootusb] - [sam. nov. 12, 23:18]
└─[$]> sudo python3 install.py  
8.0.0
running install
running build
running build_py
running build_scripts
running install_lib
copying build/lib/scripts/mbusb_cli.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/qemu.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/imager.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/persistence.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/update_cfg_file.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/iso.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/progressbar/compat.py -> /usr/local/lib/python3.5/dist-packages/scripts/progressbar
copying build/lib/scripts/progressbar/progressbar.py -> /usr/local/lib/python3.5/dist-packages/scripts/progressbar
copying build/lib/scripts/progressbar/widgets.py -> /usr/local/lib/python3.5/dist-packages/scripts/progressbar
copying build/lib/scripts/progressbar/__init__.py -> /usr/local/lib/python3.5/dist-packages/scripts/progressbar
copying build/lib/scripts/distro.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/config.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/gen.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/mbusb_gui.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/admin.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/syslinux.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/gui/ui_multibootusb.py -> /usr/local/lib/python3.5/dist-packages/scripts/gui
copying build/lib/scripts/gui/__init__.py -> /usr/local/lib/python3.5/dist-packages/scripts/gui
copying build/lib/scripts/isodump3.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/install.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/uninstall_distro.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/__init__.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/usb.py -> /usr/local/lib/python3.5/dist-packages/scripts
copying build/lib/scripts/pyudev/_errors.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/wx.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/version.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/pyqt5.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/_compat.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/device/_device.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/device
copying build/lib/scripts/pyudev/device/__init__.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/device
copying build/lib/scripts/pyudev/core.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/_util.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/monitor.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/_ctypeslib/libudev.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib
copying build/lib/scripts/pyudev/_ctypeslib/libc.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib
copying build/lib/scripts/pyudev/_ctypeslib/utils.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib
copying build/lib/scripts/pyudev/_ctypeslib/_errorcheckers.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib
copying build/lib/scripts/pyudev/_ctypeslib/__init__.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib
copying build/lib/scripts/pyudev/_qt_base.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/__init__.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/glib.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/discover.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/pyqt4.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/pyside.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev
copying build/lib/scripts/pyudev/_os/pipe.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_os
copying build/lib/scripts/pyudev/_os/poll.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_os
copying build/lib/scripts/pyudev/_os/__init__.py -> /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_os
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/mbusb_cli.py to mbusb_cli.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/qemu.py to qemu.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/imager.py to imager.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/persistence.py to persistence.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/update_cfg_file.py to update_cfg_file.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/iso.py to iso.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/progressbar/compat.py to compat.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/progressbar/progressbar.py to progressbar.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/progressbar/widgets.py to widgets.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/progressbar/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/distro.py to distro.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/config.py to config.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/gen.py to gen.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/mbusb_gui.py to mbusb_gui.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/admin.py to admin.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/syslinux.py to syslinux.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/gui/ui_multibootusb.py to ui_multibootusb.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/gui/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/isodump3.py to isodump3.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/install.py to install.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/uninstall_distro.py to uninstall_distro.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/usb.py to usb.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_errors.py to _errors.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/wx.py to wx.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/version.py to version.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/pyqt5.py to pyqt5.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_compat.py to _compat.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/device/_device.py to _device.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/device/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/core.py to core.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_util.py to _util.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/monitor.py to monitor.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib/libudev.py to libudev.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib/libc.py to libc.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib/utils.py to utils.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib/_errorcheckers.py to _errorcheckers.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_ctypeslib/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_qt_base.py to _qt_base.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/__init__.py to __init__.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/glib.py to glib.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/discover.py to discover.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/pyqt4.py to pyqt4.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/pyside.py to pyside.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_os/pipe.py to pipe.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_os/poll.py to poll.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/scripts/pyudev/_os/__init__.py to __init__.cpython-35.pyc
running install_scripts
copying build/scripts-3.5/multibootusb-pkexec -> /usr/local/bin
copying build/scripts-3.5/multibootusb -> /usr/local/bin
changing mode of /usr/local/bin/multibootusb-pkexec to 755
changing mode of /usr/local/bin/multibootusb to 755
running install_data
copying data/multibootusb.desktop -> /usr/share/applications
copying data/tools/multibootusb.png -> /usr/share/pixmaps
copying org.debian.pkexec.run-multibootusb.policy -> /usr/share/polkit-1/actions/
creating /usr/share/multibootusb
creating /usr/share/multibootusb/data
creating /usr/share/multibootusb/data/tools
copying data/tools/mbr.bin -> /usr/share/multibootusb/data/tools
copying data/version.txt -> /usr/share/multibootusb/data
copying data/tools/multibootusb.png -> /usr/share/multibootusb/data/tools
creating /usr/share/multibootusb/data/tools/dd
copying data/tools/dd/dd.exe -> /usr/share/multibootusb/data/tools/dd
copying data/tools/dd/diskio.dll -> /usr/share/multibootusb/data/tools/dd
creating /usr/share/multibootusb/data/tools/mkfs
copying data/tools/mkfs/mke2fs.exe -> /usr/share/multibootusb/data/tools/mkfs
creating /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/chain.c32 -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/bg.png -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/extlinux.cfg -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/grub.exe -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/memdisk -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/menu.c32 -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/menu.lst -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/syslinux.cfg -> /usr/share/multibootusb/data/tools/multibootusb
copying data/multibootusb/vesamenu.c32 -> /usr/share/multibootusb/data/tools/multibootusb
creating /usr/share/multibootusb/data/tools/syslinux
copying data/tools/syslinux/syslinux_modules.zip -> /usr/share/multibootusb/data/tools/syslinux
copying data/tools/syslinux/syslinux_linux.zip -> /usr/share/multibootusb/data/tools/syslinux
copying data/tools/syslinux/syslinux_linux_64.zip -> /usr/share/multibootusb/data/tools/syslinux
copying data/tools/syslinux/syslinux_windows.zip -> /usr/share/multibootusb/data/tools/syslinux
running install_egg_info
Writing /usr/local/lib/python3.5/dist-packages/multibootusb-8.0.0.egg-info
writing list of installed files to './.install_files.txt'
Installation finished.
Find multibootusb under system menu or run from terminal  using the following command...

multibootusb

You can uninstall multibootusb at any time using follwing command (with root/sudo previlage)

./uninstall.sh

┌─[tr4sk@beigebox] - [~/script/multibootusb] - [sam. nov. 12, 23:18]
└─[$]> sudo python3 /usr/local/bin/multibootusb 
Starting multibootusb GUI...
Using pyudev for detecting USB drives...
Falling back to Udisks2..
Falling back to Udisks1...
No USB device found...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scripts/usb.py", line 331, in details
    udev = details_udev(usb_disk_part)
  File "/usr/local/lib/python3.5/dist-packages/scripts/usb.py", line 172, in details_udev
    if device['ID_BUS'] == "usb" and device['DEVTYPE'] == "partition":
  File "/usr/local/lib/python3.5/dist-packages/scripts/pyudev/device/_device.py", line 961, in __getitem__
    return self.properties.__getitem__(prop)
  File "/usr/local/lib/python3.5/dist-packages/scripts/pyudev/device/_device.py", line 1088, in __getitem__
    raise KeyError(prop)
KeyError: 'ID_BUS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/multibootusb", line 98, in <module>
    start_gui()
  File "/usr/local/bin/multibootusb", line 48, in start_gui
    mbusb_gui.main_gui()
  File "/usr/local/lib/python3.5/dist-packages/scripts/mbusb_gui.py", line 589, in main_gui
    window = AppGui()
  File "/usr/local/lib/python3.5/dist-packages/scripts/mbusb_gui.py", line 87, in __init__
    self.add_device()
  File "/usr/local/lib/python3.5/dist-packages/scripts/mbusb_gui.py", line 100, in add_device
    self.onComboChange()
  File "/usr/local/lib/python3.5/dist-packages/scripts/mbusb_gui.py", line 117, in onComboChange
    self.update_gui_oncombobox(config.usb_disk)
  File "/usr/local/lib/python3.5/dist-packages/scripts/mbusb_gui.py", line 131, in update_gui_oncombobox
    self.usb_details = usb.details(usb_disk)
  File "/usr/local/lib/python3.5/dist-packages/scripts/usb.py", line 342, in details
    udisks2 = details_udisks2(usb_disk_part)
  File "/usr/local/lib/python3.5/dist-packages/scripts/usb.py", line 223, in details_udisks2
    mount_point = str(bytearray(mount_point[0]).decode('utf-8').replace(b'\x00', b''))
TypeError: Can't convert 'bytes' object to str implicitly
┌─[tr4sk@beigebox] - [~/script/multibootusb] - [sam. nov. 12, 23:18]
└─[$]> 
```

**Comment by mbusb** [comment]
Seems like you have mounted some ISO. Unmount and rerun multibootusb. If you want to start gui from terminal then you should type multibootusb-pkexec. If that fails then type 'pkexec multibootusb' because I can see that multibootusb is located in different bin directory in your log. 

Moreover, there is no requirement of installing if you have installed all required dependencies already. Simply extract the source and run multibootusb directly with admin privilege. Uninstall previous install if you are running from source. 

Let me know if that helps. I will amend the install script and guide accordingly. 

Thank you.

**Comment by mbusb** [comment]
Please try the latest version and let me know.

**Comment by Tr4sK** [comment]
Hi,

I found the bug, I had some /dev/sdb1 line inside my /etc/fstab

**Comment by mbusb** [comment]
Thank you for clarification.
