### ISSUE TITLE
hard drive crash

### ISSUE THREAD

**Issue by PowaBanga** [mbusb/multibootusb#66]
```
 sudo multibootusb-pkexec Starting multibootusb GUI...
Using pyudev for detecting USB drives...
Extracting syslinux to multibootusb directory...
Host OS is 64 bit...
Extracting syslinux 64 bit...
Extracting syslinux modules to multibootusb directory...
Using pyudev for detecting USB drives...
Using pyudev for detecting USB drives...
Persistence option is available.
Persistence option is available.
Persistence Max Size:  4.0G
Distro type detected is  ubuntu
Copying multibootusb directory to /media/powabanga/LIO_HERNOU
Copying multibootusb directory to  /media/powabanga/LIO_HERNOU##############  |
Installing  ubuntu-16.04.1-desktop-amd64.iso on /media/powabanga/LIO_HERNOU/multibootusb/ubuntu-16.04.1-desktop-amd64
ISO extracted successfully. Sync is in progress...
Executing ==> dd if=/dev/zero of=/media/powabanga/LIO_HERNOU/multibootusb/ubuntu-16.04.1-desktop-amd64/casper-rw bs=1M count=4096
dd: erreur d'écriture de «/media/powabanga/LIO_HERNOU/multibootusb/ubuntu-16.04.1-desktop-amd64/casper-rw»: Fichier trop gros
4096+0 enregistrements lus
4095+0 enregistrements écrits
4294967295 octets (4,3 GB) copiés, 149,041 s, 28,8 MB/s
Executing ==> mkfs.ext3 -F /media/powabanga/LIO_HERNOU/multibootusb/ubuntu-16.04.1-desktop-amd64/casper-rw
mke2fs 1.42.12 (29-Aug-2014)
En train de créer un système de fichiers avec 1048575 4k blocs et 262144 i-noeuds.
UUID de système de fichiers=77db4fbf-a60e-41ee-a4a2-68454ba386fa
Superblocs de secours stockés sur les blocs : 
	32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocation des tables de groupe : complété                        
Écriture des tables d'i-noeuds : complété                        
Création du journal (16384 blocs) : complété
Écriture des superblocs et de l'information de comptabilité du système de
fichiers : complété


Successfully applied filesystem...

Distro extraction completed...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 205, in install_syslinux
    syslinux_distro_dir(config.usb_disk, config.iso_link, config.distro)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 112, in syslinux_distro_dir
    config.syslinux_version = isolinux_version(isolinux_path)
  File "/usr/lib/python3/dist-packages/scripts/iso.py", line 147, in isolinux_version
    sl = list(strings(isolinux_bin_path))
  File "/usr/lib/python3/dist-packages/scripts/gen.py", line 182, in strings
    nonprintable = re.compile(b'[^%s]+' % re.escape(string.printable.encode('ascii')))
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

```
the gui don't crash, it is just that the install of the distro don't work on my usb hard drive

**Comment by mbusb** [comment]
OK got it and fixed in the development version. I will release the new
version in one or two days. This is mainly occurring due to presence of non
utf character.

**Comment by PowaBanga** [comment]
great, I am will happy to try that :)

**Comment by mbusb** [comment]
Released the bug fix version. It should solve the issue reported.

**Comment by PowaBanga** [comment]
Really thanx you !
