### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Pafzedog** [mbusb/multibootusb#67]
Installed 8.0.0-1 on Ubuntu 16.04 with deb.
here is return of command "multibootusb-pkexec" (same with pkexec multibootusb)

`$ multibootusb-pkexec 
Starting multibootusb GUI...
Using pyudev for detecting USB drives...
Falling back to Udisks2..
Falling back to Udisks1...
No USB device found...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 331, in details
    udev = details_udev(usb_disk_part)
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 172, in details_udev
    if device['ID_BUS'] == "usb" and device['DEVTYPE'] == "partition":
  File "/usr/lib/python3/dist-packages/scripts/pyudev/device/_device.py", line 961, in __getitem__
    return self.properties.__getitem__(prop)
  File "/usr/lib/python3/dist-packages/scripts/pyudev/device/_device.py", line 1088, in __getitem__
    raise KeyError(prop)
KeyError: 'ID_BUS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 98, in <module>
    start_gui()
  File "/usr/bin/multibootusb", line 48, in start_gui
    mbusb_gui.main_gui()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 589, in main_gui
    window = AppGui()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 87, in __init__
    self.add_device()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 100, in add_device
    self.onComboChange()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 117, in onComboChange
    self.update_gui_oncombobox(config.usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 131, in update_gui_oncombobox
    self.usb_details = usb.details(usb_disk)
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 342, in details
    udisks2 = details_udisks2(usb_disk_part)
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 223, in details_udisks2
    mount_point = str(bytearray(mount_point[0]).decode('utf-8').replace(b'\x00', b''))
TypeError: Can't convert 'bytes' object to str implicitly
`

**Comment by mbusb** [comment]
Please try the latest version 8.1.0 and give a feedback.

**Comment by Pafzedog** [comment]
ok, it's fixed :+1:
