### ISSUE TITLE
"Installing Syslinux ..." hangs

### ISSUE THREAD

**Issue by shoodle** [mbusb/multibootusb#69]
I installed python3-multibootusb_8.0.0-1_all.deb on my system.

Running "multibootusb" on the command line on Debian (3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux) with or without "sudo". In both cases the selected ISO file is installed but afterwards "syslinux" cannot be installed.

```
ISO extracted successfully. Sync is in progress...############################|
Distro extraction completed...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 205, in install_syslinux
    syslinux_distro_dir(config.usb_disk, config.iso_link, config.distro)
  File "/usr/lib/python3/dist-packages/scripts/syslinux.py", line 112, in syslinux_distro_dir
    config.syslinux_version = isolinux_version(isolinux_path)
  File "/usr/lib/python3/dist-packages/scripts/iso.py", line 147, in isolinux_version
    sl = list(strings(isolinux_bin_path))
  File "/usr/lib/python3/dist-packages/scripts/gen.py", line 182, in strings
    nonprintable = re.compile(b'[^%s]+' % re.escape(string.printable.encode('ascii')))
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
```

**Comment by mbusb** [comment]
The bug has been fixed in development version. Should be released in next few days.

**Comment by mbusb** [comment]
Released the bug fix version.
