### ISSUE TITLE
The Rosa Linux Fresh R8 is not work

### ISSUE THREAD

**Issue by Survolog** [mbusb/multibootusb#80]
After recording on a USB stick and booted they don't work.
I see it on UEFI and legacy in menu on F8 key's, but
My PC OS boot, when I choose UEFI
"_" blink, when I choose legacy.

Also
When I choose "All Drives", MultiBootUSB is die.
When I start MultiBootUSB as sudo multibootusb and choose ISO with ROSA, it die too and console printed:

```
survolog@survolog-desktop ~ $ sudo multibootusb
Starting multibootusb GUI...
Using pyudev for detecting USB drives...
Falling back to Udisks2..
Falling back to Udisks1...
No USB device found...
No USB device found...
Cleaning old multibootusb directory...
Extracting syslinux to multibootusb directory...
Host OS is 64 bit...
Extracting syslinux 64 bit...
Extracting syslinux modules to multibootusb directory...
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 361, in details
    udev = details_udev(usb_disk_part)
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 199, in details_udev
    if device['ID_BUS'] in ("usb", "scsi") and device['DEVTYPE'] == "partition":
  File "/usr/lib/python3.4/site-packages/scripts/pyudev/device/_device.py", line 961, in __getitem__
    return self.properties.__getitem__(prop)
  File "/usr/lib/python3.4/site-packages/scripts/pyudev/device/_device.py", line 1088, in __getitem__
    raise KeyError(prop)
KeyError: 'ID_BUS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/scripts/mbusb_gui.py", line 183, in browse_iso
    per_availability = persistence.persistence_distro(config.distro, config.usb_disk, config.iso_link)[0]
  File "/usr/lib/python3.4/site-packages/scripts/persistence.py", line 28, in persistence_distro
    usb_details = usb.details(usb_disk)
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 372, in details
    udisks2 = details_udisks2(usb_disk_part)
  File "/usr/lib/python3.4/site-packages/scripts/usb.py", line 244, in details_udisks2
    device = bd.Get('org.freedesktop.UDisks2.Block', 'Device', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/UDisks2/block_devices
Аварийный останов
survolog@survolog-desktop ~ $ 
```

**Comment by mbusb** [comment]
Fixed in the new release. Also ROSA Linux should boot properly now.
