### ISSUE TITLE
ImportError: No module named 'six'

### ISSUE THREAD

**Issue by ntilotta** [mbusb/multibootusb#82]
Debian Testing / KDE

> Starting multibootusb GUI...
Traceback (most recent call last):
  File "/usr/bin/multibootusb", line 102, in <module>
    start_gui()
  File "/usr/bin/multibootusb", line 52, in start_gui
    mbusb_gui.main_gui()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 614, in main_gui
    window = AppGui()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 88, in __init__
    self.add_device()
  File "/usr/lib/python3/dist-packages/scripts/mbusb_gui.py", line 100, in add_device
    detected_device = usb.list()
  File "/usr/lib/python3/dist-packages/scripts/usb.py", line 90, in list
    from . import pyudev
  File "/usr/lib/python3/dist-packages/scripts/pyudev/__init__.py", line 42, in <module>
    from ._errors import DeviceNotFoundAtPathError
  File "/usr/lib/python3/dist-packages/scripts/pyudev/_errors.py", line 34, in <module>
    from six import add_metaclass
ImportError: No module named 'six'

**Comment by mbusb** [comment]
I have included python3-six as a dependency in the new release.
