### ISSUE TITLE
Exception thrown when replugging a newly formated device

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#84]
### Issue

Due to #83, when I reformat the device to VFAT (using `gnome-disk`, if it matters):

1. The device is automatically ejected
2. I physically unplug it and replug it in the *same USB port*
3. I start `multibootusb` again, but it then throws the following exception:

```
% sudo ./multibootusb
Starting multibootusb GUI...
Using pyudev for detecting USB drives...
No USB device found...
Cleaning old multibootusb directory...
Extracting syslinux to multibootusb directory...
Host OS is 64 bit...
Extracting syslinux 64 bit...
Extracting syslinux modules to multibootusb directory...
Traceback (most recent call last):
  File "/home/gautier/multibootusb/scripts/usb.py", line 370, in details
    udev = details_udev(usb_disk_part)
  File "/home/gautier/multibootusb/scripts/usb.py", line 229, in details_udev
    if not mount_point == '':
UnboundLocalError: local variable 'mount_point' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gautier/multibootusb/scripts/mbusb_gui.py", line 183, in browse_iso
    per_availability = persistence.persistence_distro(config.distro, config.usb_disk, config.iso_link)[0]
  File "/home/gautier/multibootusb/scripts/persistence.py", line 28, in persistence_distro
    usb_details = usb.details(usb_disk)
  File "/home/gautier/multibootusb/scripts/usb.py", line 381, in details
    udisks2 = details_udisks2(usb_disk_part)
  File "/home/gautier/multibootusb/scripts/usb.py", line 253, in details_udisks2
    device = bd.Get('org.freedesktop.UDisks2.Block', 'Device', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/UDisks2/block_devices
```

### Workaround

If I wait a few more seconds (around 30s), I can start the application and it works as expected.

**Comment by mbusb** [comment]
I think it is mainly due to the time taken by your system to mount your USB.

**Comment by mbusb** [comment]
The next version (8.5.0) should fix this issue. Already implemented in the development version.
