### ISSUE TITLE
Improve/Facilitate user experience

### ISSUE THREAD

**Issue by bagage** [mbusb/multibootusb#87]
I just experienced the same issue as in #38, eg. my USB key had no partitions and thus was not listed in the first tab even if it was found in the second one (ISO imager).
I know that this is as expected, but from a user point of view, it would be very cool if:

- [ ] Some tooltip could be displayed near "Detect Drives", such as: 
> To make your USB stick appears, it must be FAT32 and must have at least one partition.
- [ ] The `Browse ISO` button is grayed out until a drive is selected, or something similar to the `Create` button (a popup). Because currently, the application will just crash:
```
Extracting syslinux modules to multibootusb directory...
Traceback (most recent call last):
  File "/home/gautier/code/multibootusb/scripts/usb.py", line 370, in details
    udev = details_udev(usb_disk_part)
  File "/home/gautier/code/multibootusb/scripts/usb.py", line 229, in details_udev
    if not mount_point == '':
UnboundLocalError: local variable 'mount_point' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gautier/code/multibootusb/scripts/mbusb_gui.py", line 183, in browse_iso
    per_availability = persistence.persistence_distro(config.distro, config.usb_disk, config.iso_link)[0]
  File "/home/gautier/code/multibootusb/scripts/persistence.py", line 28, in persistence_distro
    usb_details = usb.details(usb_disk)
  File "/home/gautier/code/multibootusb/scripts/usb.py", line 381, in details
    udisks2 = details_udisks2(usb_disk_part)
  File "/home/gautier/code/multibootusb/scripts/usb.py", line 253, in details_udisks2
    device = bd.Get('org.freedesktop.UDisks2.Block', 'Device', dbus_interface='org.freedesktop.DBus.Properties')
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/UDisks2/block_devices
```
- [ ] Remove the weird `Close` button near `Create`. I am not sure what it should be for, but if you want to quit the application, why not use the standard cross button on the window?

**Comment by alindt** [comment]
@bagage, check out the latest devel branch UI ang give us feedback/impressions

**Comment by alindt** [comment]
@bagage, give the [latest release](https://github.com/mbusb/multibootusb/releases) (8.6.0) a try

**Comment by mbusb** [comment]
Hope that user experience is improved for both CLI and GUI.
